/**
 * Server and tile configuration.
 *
 * In development the React Native Metro server runs on your workstation.
 * The aviation data is served by the web Vite dev server (port 5173).
 */
import { layers, LIGHT } from '@protomaps/basemaps'
import type { StyleSpecification } from '@maplibre/maplibre-gl-style-spec'

import { Platform } from 'react-native'

const devBase =
  Platform.OS === 'android'
    // adb reverse tcp:5200 tcp:5200 (see build:android:device) forwards the
    // device's localhost:5200 to the host workstation — no LAN IP needed,
    // and unlike a hardcoded LAN IP this never goes stale when the
    // workstation reconnects to Wi-Fi and gets a new address.
    ? (process.env.EXPO_PUBLIC_API_BASE_ANDROID ?? 'http://localhost:5200')
    : 'http://localhost:5200'

/** Base URL of the open-vfr API server (auth, weather, NOTAM). Override via EXPO_PUBLIC_API_BASE. */
export const API_BASE: string =
  (process.env.EXPO_PUBLIC_API_BASE ?? '') || devBase

/** Base URL for static GeoJSON tile files (served by Vite in dev, nginx in prod).
 *  Defaults to API_BASE. Override via EXPO_PUBLIC_TILE_BASE. */
export const TILE_BASE: string =
  (process.env.EXPO_PUBLIC_TILE_BASE ?? '') || API_BASE

/**
 * Base URL for the OpenSky traffic endpoints (/api/traffic/*).
 *
 * Defaults to API_BASE, but you should override this explicitly in most
 * self-hosted setups: the traffic poller typically runs against a single
 * OpenSky account with a tight daily credit quota (see apps/api/src/traffic.ts).
 * Running a second independent poller from local dev would silently
 * double-burn that account's quota using the same OpenSky credentials.
 * Local dev should read live traffic from an already-running poller
 * instead of starting its own, unless you've configured a separate OpenSky
 * account for the local docker-compose `api` service.
 * Override via EXPO_PUBLIC_TRAFFIC_BASE.
 */
export const TRAFFIC_BASE: string =
  (process.env.EXPO_PUBLIC_TRAFFIC_BASE ?? '') || API_BASE

/** Base URL for Martin vector tile server.
 *  Dev: TILE_BASE with its port swapped to :5100 (requires `adb reverse tcp:5100 tcp:5100`).
 *  Prod: nginx proxies Martin at /martin (see docker-compose.yml + docker/nginx.conf),
 *  so when TILE_BASE has no explicit port (e.g. a bare https:// domain) the port-swap
 *  regex can't match — append /martin instead. Without this branch MARTIN_BASE silently
 *  fell back to TILE_BASE unchanged, and MapLibre would request landuse tiles from the
 *  web app's root and get back HTML, producing "unknown pbf field type exception".
 *  Override via EXPO_PUBLIC_MARTIN_BASE.
 *
 *  Currently unused — landuse (the last consumer) moved to LANDUSE_PMTILES_URL
 *  below (static R2 file, retired from Postgres/Martin). Kept, not deleted:
 *  Martin still exists as a service for genuinely-dynamic future data
 *  (NOTAM/METAR/live airspace activation, user-generated content), so this
 *  constant will have a real consumer again once one of those ships. */
export const MARTIN_BASE: string =
  (process.env.EXPO_PUBLIC_MARTIN_BASE ?? '') ||
  (/:(\d{4,5})(\/|$)/.test(TILE_BASE)
    ? TILE_BASE.replace(/:(\d{4,5})(\/|$)/, ':5100$2')
    : `${TILE_BASE.replace(/\/$/, '')}/martin`)

/** GeoJSON tile URLs — same files served by the web project */
export const TILE_URLS = {
  airspace:          `${TILE_BASE}/tiles/se-airspace.geojson`,
  aerodromes:        `${TILE_BASE}/tiles/se-aerodromes.geojson`,
  navaids:           `${TILE_BASE}/tiles/se-navaids.geojson`,
  waypoints:         `${TILE_BASE}/tiles/se-waypoints.geojson`,
  runways:           `${TILE_BASE}/tiles/se-runways.geojson`,
  runwayThresholds:  `${TILE_BASE}/tiles/se-runway-thresholds.geojson`,
  obstacles:         `${TILE_BASE}/tiles/se-obstacles.geojson`,
  landmarks:         `${TILE_BASE}/tiles/se-landmarks.geojson`,
  water:             `${TILE_BASE}/tiles/se-water.geojson`,
} as const

/**
 * Landuse PMTiles URL — retired from Postgres/Martin (was
 * `${MARTIN_BASE}/landuse_tiles/{z}/{x}/{y}?country=SE`), now a static
 * per-country .pmtiles file from object storage, same pattern as
 * `createProtomapsStyle`'s basemap.pmtiles below. See
 * apps/web/src/styles/map-style.ts `getLanduseSource()` and
 * docs/self-hosting.md.
 *
 * MapLibre Native 11+'s <VectorSource> accepts a `url` prop directly
 * (TileJSON/pmtiles), same as the `tiles` array it replaces here — no
 * separate protocol registration needed beyond what basemap.pmtiles already
 * requires.
 */
export const LANDUSE_PMTILES_URL = `pmtiles://${TILE_BASE}/tiles/se-landuse.pmtiles`

/**
 * Relief hillshade raster-dem PMTiles (Terrarium encoding), same static file
 * generated by scripts/hillshade_to_pmtiles.sh and shipped alongside
 * basemap.pmtiles / se-landuse.pmtiles. Wired into AviationMap.tsx via
 * <RasterDEMSource>/<Layer type="hillshade"> (toggle: MapDisplaySheet's
 * Terrain section, LayerState.hillshade) and offlineCache.ts's optional
 * asset list. Verified supported on both platforms at the native binary
 * level, not just the JS type declarations — see AGENTS.md MapLibre RN
 * gotchas.
 */
export const HILLSHADE_PMTILES_URL = `pmtiles://${TILE_BASE}/tiles/se-hillshade.pmtiles`

/**
 * Vector contour-line PMTiles (source-layer 'contours', `elev_m` property),
 * same static file generated by scripts/contours_to_pmtiles.sh. Unlike
 * HILLSHADE_PMTILES_URL above, actual <VectorSource>/<Layer type="line">
 * + <Layer type="symbol"> wiring in the native map component is NOT yet
 * done — config wired for offline caching only so far.
 */
export const CONTOURS_PMTILES_URL = `pmtiles://${TILE_BASE}/tiles/se-contours.pmtiles`

/**
 * MapLibre GL style URL for the basemap.
 *
 * OpenFreeMap (https://openfreemap.org) is a completely free, no-API-key
 * service built on the same Protomaps/OpenMapTiles stack as the web basemap.
 * ODbL licence; self-hostable.
 *
 * Alternatives (also free, no key):
 *   - 'https://tiles.openfreemap.org/styles/bright'
 *   - 'https://tiles.openfreemap.org/styles/positron'
 */
export const BASEMAP_STYLE_URL =
  (process.env.EXPO_PUBLIC_BASEMAP_URL ?? '') ||
  'https://tiles.openfreemap.org/styles/liberty'

/** ESRI World Imagery — free XYZ satellite tiles, no API key. */
export const SATELLITE_STYLE = {
  version: 8 as const,
  sources: {
    satellite: {
      type: 'raster' as const,
      tiles: ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],
      tileSize: 256,
      maxzoom: 18,
      attribution: 'Tiles © Esri',
    },
  },
  layers: [{ id: 'satellite', type: 'raster' as const, source: 'satellite' }],
}

/**
 * Protomaps basemap style — identical to the web PWA.
 * Tiles are served from the Vite dev server (same PMTiles file).
 * In production, TILE_BASE points to the hosted server.
 *
 * MapLibre Native 11+ supports pmtiles:// natively.
 * URL format: pmtiles://<http(s)-url-of-pmtiles-file>
 */
export function createProtomapsStyle(pmtilesOverrideUrl?: string): StyleSpecification {
  const pmtilesUrl = `pmtiles://${pmtilesOverrideUrl ?? `${TILE_BASE}/tiles/basemap.pmtiles`}`
  return {
    version: 8,
    glyphs:  'https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf',
    sprite:  'https://protomaps.github.io/basemaps-assets/sprites/v4/light',
    sources: {
      protomaps: {
        type:        'vector',
        url:         pmtilesUrl,
        attribution: '<a href="https://protomaps.com">Protomaps</a> © <a href="https://openstreetmap.org">OpenStreetMap</a>',
      } as StyleSpecification['sources'][string],
    },
    layers: layers('protomaps', LIGHT, { lang: 'sv' }) as StyleSpecification['layers'],
  }
}

/** Default map centre — Sweden */
export const DEFAULT_CENTER: [number, number] = [17.0, 62.0]  // [lng, lat]
export const DEFAULT_ZOOM = 5

/** Airspace ceiling default (FL095 = 9,500 ft) */
export const DEFAULT_AIRSPACE_CEILING_FT = 9_500
