import type { StyleSpecification, FilterSpecification, ExpressionSpecification } from 'maplibre-gl'
import { layers, LIGHT } from '@protomaps/basemaps'
import { AIRSPACE_COLORS as AC } from '@open-vfr/shared/airspaceColors'
import { AERODROME_COLORS, NAVAID_COLORS, WAYPOINT_COLORS, OBSTACLE_COLORS, RUNWAY_COLORS } from '@open-vfr/shared/featureColors'
import {
  RUNWAY_LABEL_DEFAULT_SIZE,
  RUNWAY_LABEL_DEFAULT_OPACITY,
  RUNWAY_LABEL_DEFAULT_COLOR,
  RUNWAY_LABEL_DEFAULT_HALO,
} from '@open-vfr/shared/runwayWind'
import { WIND_BARB_COLOR } from '../utils/windBarbIcons'
import { TILES_BASE_URL } from '../utils/env'
import { versionedTileUrl } from '@open-vfr/shared/tileManifest'

// Airspace on-map label text — class/type short code + altitude range, placed
// along the boundary line (symbol-placement: 'line') so it repeats around the
// perimeter and stays visible even when the polygon's centre is off-screen.
// Built from our own class/type/lower/upper GeoJSON properties via a style
// expression, rather than a precomputed label property.
const AIRSPACE_LABEL_TEXT_FIELD = [
  'concat',
  ['match', ['get', 'type'], 'CTR', 'CTR', ['get', 'class']],
  '  ·  ',
  ['get', 'lower'],
  ' – ',
  ['get', 'upper'],
] as unknown as ExpressionSpecification

// Restricted areas (R) and TRAs already have a unique, self-describing
// designator in their 'name' property (e.g. 'ESR1 ESRANGE', 'ESTRA80') —
// showing that is far more useful than the generic 'R'/'TRA' class code.
const AIRSPACE_RESTRICTED_LABEL_TEXT_FIELD = [
  'concat',
  ['get', 'name'],
  '  ·  ',
  ['get', 'lower'],
  ' – ',
  ['get', 'upper'],
] as unknown as ExpressionSpecification

// ── Martin tile server ────────────────────────────────────────────────────────
// URL is injected via VITE_MARTIN_URL at build/dev time.
// In production VITE_MARTIN_URL=/martin (a relative path). MapLibre passes
// tile URLs to its internal web worker which calls new Request(url) — workers
// have no base URL to resolve relative paths against, so the request fails.
// Resolve against location.origin at runtime to guarantee absolute URLs.
export const MARTIN_URL: string = (() => {
  const raw = (import.meta.env.VITE_MARTIN_URL as string | undefined) ?? 'http://localhost:5100'
  if (raw.startsWith('/') && typeof location !== 'undefined') {
    return location.origin + raw
  }
  return raw
})()

// Static per-country landuse PMTiles source spec (object storage, tiled by
// tippecanoe -- see docs/self-hosting.md). Replaces the old Martin-backed
// getLanduseUrl(). Exported so
// MapView.tsx can rebuild this source on region change (full removeSource/
// addSource swap -- PMTiles url-based vector sources have no setTiles()).
export function getLanduseSource(country: string) {
  return {
    type: 'vector' as const,
    url: `pmtiles://${versionedTileUrl(TILES_BASE_URL, `${country}-landuse.pmtiles`)}`,
    // Tiled at -Z0 -z12 (scripts/prepare-tiles.sh). MapLibre overzooms
    // vector data automatically so the layer renders at any zoom level.
    maxzoom: 12,
    attribution:
      '© <a href="https://openstreetmap.org">OpenStreetMap</a> contributors (ODbL)',
  }
}

// Static per-country hillshade PMTiles source spec (raster-dem, R2).
// Generated by scripts/hillshade_to_pmtiles.sh from Copernicus GLO-30 DEM
// (open, no API key) via `gdaldem hillshade` + `gdal2tiles.py` + `pmtiles convert`.
// Terrarium PNG encoding — same as the AWS Terrain Tiles public bucket, so
// this source can be pointed at that bucket directly for prototyping by
// swapping the url below (not done by default: keeps the static-file,
// no-external-runtime-dependency architecture consistent with every other layer).
// Mirrors getLanduseSource()'s region-swap wiring 1:1 — see MapView.tsx.
// Static per-country contour-line PMTiles source spec (vector, R2).
// Generated by scripts/contours_to_pmtiles.sh from the same Copernicus
// GLO-30 DEM mosaic as getHillshadeSource() (scripts/dem_mosaic.sh caches
// the download so it's shared, not fetched twice). Vector features carry
// an `elev_m` numeric property. Mirrors getLanduseSource()'s region-swap
// wiring 1:1 — see MapView.tsx.
export function getContoursSource(country: string) {
  return {
    type: 'vector' as const,
    url: `pmtiles://${versionedTileUrl(TILES_BASE_URL, `${country}-contours.pmtiles`)}`,
    // Tiled at -Z6 -z12 (scripts/contours_to_pmtiles.sh) — contours only
    // matter at closer-in VFR planning zooms, unlike landuse/basemap. Must
    // match the script's real -z value exactly (was wrongly declared 14
    // here while the script actually caps at 12 -- same class of bug as
    // getHillshadeSource()'s maxzoom mismatch above, see its comment for
    // the full explanation). Vector sources degrade less catastrophically
    // than raster-dem for a too-high declared maxzoom (a fetch to a
    // non-existent tile just 404s/empty-tiles rather than hanging forever),
    // which is exactly why this bug presented as "intermittent, sometimes
    // works after panning" instead of hillshade's total, deterministic
    // failure -- panning happens to change which zoom/tile is requested,
    // occasionally landing within the real 6-12 range.
    minzoom: 6,
    maxzoom: 12,
    attribution:
      'Copernicus DEM GLO-30 — © ESA / European Union, doi:10.5270/ESA-c5d3d65',
  }
}

export function getHillshadeSource(country: string) {
  return {
    type: 'raster-dem' as const,
    url: `pmtiles://${versionedTileUrl(TILES_BASE_URL, `${country}-hillshade.pmtiles`)}`,
    encoding: 'terrarium' as const,
    // Must match the archive's REAL base zoom, not a desired one. GDAL's
    // MBTiles driver (scripts/hillshade_to_pmtiles.sh) auto-picks the base
    // (finest) zoom from dem_mosaic.sh's downsampled ~90m/px input raster --
    // that resolution lands at z10, confirmed via the archive's own PMTiles
    // header (`maxZoom: 10`). gdaladdo's overview pyramid only ever produces
    // COARSER zooms below the base, never finer ones -- there is no z11/z12
    // data in this file. A mismatched (too-high) declared maxzoom here isn't
    // just cosmetic: MapLibre trusts it and requests tiles up to that zoom
    // believing they exist; when pmtiles.js's raster-dem tile resolution hits
    // a zoom beyond the archive's real ceiling, it doesn't error or overzoom
    // -- the tile hangs in 'loading' state forever (confirmed via MapLibre's
    // internal tileManagers['osm-hillshade']._inViewTiles state, all stuck
    // 'loading' indefinitely, zero underlying network requests). Declaring
    // the TRUE maxzoom instead lets MapLibre's normal overzoom path kick in
    // above z10 (reuse + upscale the z10 tile), which works fine -- the bug
    // is only ever hit by requesting UP TO a maxzoom that isn't backed by
    // real tile data, not by exceeding a correctly-declared one.
    maxzoom: 10,
    // Copernicus DEM license (free, open, commercial use permitted) requires
    // citing the dataset DOI — see https://doi.org/10.5270/ESA-c5d3d65 and
    // docs/architecture.md licensing table.
    attribution:
      'Copernicus DEM GLO-30 — © ESA / European Union, doi:10.5270/ESA-c5d3d65',
  }
}

// ── Satellite basemap ─────────────────────────────────────────────────────
// ESRI World Imagery — free XYZ tiles, no API key required.
// Note: ESRI's tile path order is {z}/{y}/{x} (row/col), not {z}/{x}/{y}.
export const SATELLITE_TILES = [
  'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
]

// Layer IDs from the @protomaps/basemaps LIGHT theme — used by MapView to
// hide the vector basemap when switching to satellite mode without a style reload.
export const PROTOMAPS_LAYER_IDS: readonly string[] = (
  layers('protomaps', LIGHT, { lang: 'sv' }) as StyleSpecification['layers']
)
  .map((l) => l.id)
  .filter((id): id is string => typeof id === 'string')

// Airspace border layers with default (vector) and boosted (satellite) line-widths.
// In satellite mode widths are increased so class boundaries remain legible over imagery.
export const AIRSPACE_BORDER_WIDTHS: { id: string; vector: number | ExpressionSpecification; sat: number }[] = [
  { id: 'airspace-border-c',          vector: ['match', ['get', 'type'], 'CTR', 2.0, 1.4], sat: 2.5 },
  { id: 'airspace-border-d',          vector: 1.2,  sat: 2.0 },
  { id: 'airspace-border-e',          vector: 1.5,  sat: 2.0 },
  { id: 'airspace-border-g',          vector: 1.0,  sat: 1.5 },
  { id: 'airspace-border-restricted', vector: ['match', ['get', 'class'], 'R', 1.8, 1.2], sat: 2.5 },
  { id: 'airspace-border-activity',   vector: 1.0,  sat: 1.5 },
]

// Aviation label layers whose text-halo is boosted for readability over satellite imagery.
export const AVIATION_LABEL_LAYERS = [
  'aerodromes-label',
  'navaids-vor-label',
  'navaids-ndb-label',
  'waypoints-mrp-label',
  'waypoints-rp-label',
  'obstacles-label',
  'landmarks-label',
  'user-waypoints-label',
  'airspace-label-c',
  'airspace-label-d',
  'airspace-label-e',
  'airspace-label-g',
  'airspace-label-restricted',
  'airspace-label-activity',
] as const

// Runway wind-highlight defaults/builder now live in
// @open-vfr/shared/runwayWind (buildRunwayWindHighlight, RUNWAY_LABEL_DEFAULT_*,
// RUNWAY_FAVORED_*) so native's AviationMap.tsx can share the exact same
// favored-end styling instead of maintaining a second copy.

// ── Layer group definitions ─────────────────────────────────────────────────
// Each entry maps one toggle in the UI to one or more MapLibre layer IDs.
// Visibility is controlled via map.setLayoutProperty(id, 'visibility', ...).
// `section` is the heading shown above the first group with that value.
export interface LayerGroup {
  id: string
  label: string
  cssClass: string  // CSS module class name (e.g. 'groupControlled')
  layerIds: string[]
  defaultOn: boolean
  section: string   // Section heading — groups with same value share one header
}

// ── Altitude filter ─────────────────────────────────────────────────────────
// Base filters per layer — mirrors the filter set on each layer in getMapStyle().
// Stored here so MapView can rebuild combined filters without relying on
// map.getFilter() timing (which varies with styledata/load event ordering).
export const AIRSPACE_BASE_FILTERS: Readonly<Record<string, FilterSpecification>> = {
  'airspace-fill-c':            ['==', ['get', 'class'], 'C'],
  'airspace-inset-c':           ['==', ['get', 'class'], 'C'],
  'airspace-border-c':          ['==', ['get', 'class'], 'C'],
  'airspace-label-c':           ['==', ['get', 'class'], 'C'],
  'airspace-fill-d':            ['==', ['get', 'class'], 'D'],
  'airspace-inset-d':           ['==', ['get', 'class'], 'D'],
  'airspace-border-d':          ['==', ['get', 'class'], 'D'],
  'airspace-label-d':           ['==', ['get', 'class'], 'D'],
  'airspace-fill-e':            ['==', ['get', 'class'], 'E'],
  'airspace-inset-e':           ['==', ['get', 'class'], 'E'],
  'airspace-border-e':          ['==', ['get', 'class'], 'E'],
  'airspace-label-e':           ['==', ['get', 'class'], 'E'],
  'airspace-fill-g':            ['==', ['get', 'class'], 'G'],
  'airspace-inset-g':           ['==', ['get', 'class'], 'G'],
  'airspace-border-g':          ['==', ['get', 'class'], 'G'],
  'airspace-label-g':           ['==', ['get', 'class'], 'G'],
  'airspace-fill-restricted':   ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
  'airspace-inset-restricted':  ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
  'airspace-border-restricted': ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
  'airspace-label-restricted':  ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
  'airspace-fill-activity':     ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
  'airspace-inset-activity':    ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
  'airspace-border-activity':   ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
  'airspace-label-activity':    ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
}

// Default ceiling in feet. FL095 (9500 ft) sits below most CTA lower limits,
// giving a sensible out-of-the-box view for VFR en-route flight.
export const DEFAULT_CEILING_FT = 9500

// Single source of truth for the initial region shown before any user
// region-selection UI exists (Phase 2). Used both as MapView's initial
// `region` state default AND as the hardcoded country passed to
// getLanduseSource()/getHillshadeSource() inside the static getMapStyle()
// sources object below — keeping these in one place avoids the two spots
// silently drifting out of sync.
export const DEFAULT_REGION = 'se'

// Build a MapLibre filter: show only features whose lower limit ≤ ceilingFt.
export function buildAltitudeFilter(
  baseFilter: FilterSpecification,
  ceilingFt: number,
): FilterSpecification {
  return ['all', baseFilter, ['<=', ['get', 'lower_ft'], ceilingFt]] as FilterSpecification
}

export const LAYER_GROUPS: LayerGroup[] = [
  {
    id: 'classC',
    // Controlled airspace zones — CTR (Control Zone) and TMA (Terminal Area).
    // These are the ICAO Class C designated polygons in the OFM data.
    label: 'CTR / TMA',
    cssClass: 'groupClassC',
    layerIds: ['airspace-fill-c', 'airspace-inset-c', 'airspace-border-c', 'airspace-label-c'],
    defaultOn: true,
    section: 'Airspace',
  },
  {
    id: 'classD',
    // Danger areas — military/hazardous activity zones (OFM type=D).
    // Stored as class=D in GeoJSON; distinct from ICAO Class D airspace.
    label: 'Danger Areas',
    cssClass: 'groupClassD',
    layerIds: ['airspace-fill-d', 'airspace-inset-d', 'airspace-border-d', 'airspace-label-d'],
    defaultOn: true,
    section: 'Airspace',
  },
  {
    id: 'classE',
    // Class E designated airspace polygons (e.g. cross-border TMAs).
    label: 'Class E',
    cssClass: 'groupClassE',
    layerIds: ['airspace-fill-e', 'airspace-inset-e', 'airspace-border-e', 'airspace-label-e'],
    defaultOn: true,
    section: 'Airspace',
  },
  {
    id: 'classG',
    // Designated zones within uncontrolled airspace:
    // RMZ (Radio Mandatory Zone) and ATZ (Aerodrome Traffic Zone).
    // Note: does NOT toggle all Class G airspace — only these specific zones.
    label: 'RMZ / ATZ',
    cssClass: 'groupClassG',
    layerIds: ['airspace-fill-g', 'airspace-inset-g', 'airspace-border-g', 'airspace-label-g'],
    defaultOn: true,
    section: 'Airspace',
  },
  {
    id: 'restricted',
    // R = Restricted / Prohibited areas, TRA = Temporary Reserved Areas
    label: 'Restricted / TRA',
    cssClass: 'groupRestricted',
    layerIds: ['airspace-fill-restricted', 'airspace-inset-restricted', 'airspace-border-restricted', 'airspace-label-restricted'],
    defaultOn: true,
    section: 'Airspace',
  },
  {
    id: 'activity',
    // Activity areas: GLDR = Glider areas, MODEL = Model aircraft / UAS zones
    label: 'Glider / Model Areas',
    cssClass: 'groupActivity',
    layerIds: ['airspace-fill-activity', 'airspace-inset-activity', 'airspace-border-activity', 'airspace-label-activity'],
    defaultOn: false,
    section: 'Airspace',
  },
  {
    id: 'navaidsVOR',
    // VOR (and DVOR) navaids — OFM OFMX source. 24 points across Sweden.
    // Shows the 3-letter identifier + frequency from zoom 8+.
    label: 'VOR',
    cssClass: 'groupNavaidsVOR',
    layerIds: ['navaids-vor-icon', 'navaids-vor-label'],
    defaultOn: true,
    section: 'Navigation',
  },
  {
    id: 'navaidsNDB',
    // NDB (Non-Directional Beacon) navaids — OFM OFMX source. 66 points.
    label: 'NDB',
    cssClass: 'groupNavaidsNDB',
    layerIds: ['navaids-ndb-icon', 'navaids-ndb-label'],
    defaultOn: true,
    section: 'Navigation',
  },
  {
    id: 'waypointsMRP',
    // VFR Mandatory Reporting Points (MRP) — OFM OFMX source. 188 points.
    // These are compulsory position reports when entering a CTR/TMA.
    label: 'MRP (Reporting Pts)',
    cssClass: 'groupWaypointsMRP',
    layerIds: ['waypoints-mrp-icon', 'waypoints-mrp-label'],
    defaultOn: true,
    section: 'Navigation',
  },
  {
    id: 'waypointsRP',
    // VFR Reporting Points (RP) — non-mandatory. 104 points.
    label: 'VFR Waypoints',
    cssClass: 'groupWaypointsRP',
    layerIds: ['waypoints-rp-icon', 'waypoints-rp-label'],
    defaultOn: false,
    section: 'Navigation',
  },
  {
    id: 'aerodromes',
    label: 'Aerodromes',
    cssClass: 'groupAerodromes',
    layerIds: ['aerodromes-icon', 'aerodromes-label', 'aerodromes-atc-ring', 'aerodromes-notam-hint'],
    defaultOn: true,
    section: 'Navigation',
  },
  {
    id: 'runways',
    // OFM runway centre-lines with width-accurate rendering + threshold labels.
    // Also includes OSM taxiways/aprons served from PostGIS via Martin.
    label: 'Runways & taxiways',
    cssClass: 'groupRunways',
    layerIds: [
      'taxiway-line',
      'runways-outline',
      'runways-line',
      'runway-threshold-label',
      'taxiway-label',
    ],
    defaultOn: true,
    section: 'Navigation',
  },
  {
    id: 'obstacles',
    // Aviation obstacles: wind turbines, towers, chimneys, tall buildings.
    // Source: OpenAIP (CC BY-NC 4.0). 3 667 features across Sweden.
    // Wind turbines dominate (2 500+). Shown from zoom 9 to avoid clutter.
    label: 'Obstacles',
    cssClass: 'groupObstacles',
    layerIds: ['obstacles-circle', 'obstacles-label'],
    defaultOn: true,
    section: 'Navigation',
  },
  {
    id: 'landmarks',
    // VFR ground landmarks for dead-reckoning: churches, masts, windmills,
    // water towers, chimneys. Source: OpenStreetMap (ODbL) via Overpass API.
    // Deduplicated against OpenAIP obstacles at data-prep time.
    // Off by default — pilots enable when planning low-level routes.
    label: 'Landmarks (OSM)',
    cssClass: 'groupLandmarks',
    layerIds: ['landmarks-icon', 'landmarks-label'],
    defaultOn: false,
    section: 'Navigation',
  },
  {
    id: 'userWaypoints',
    // User-defined custom waypoints persisted in RxDB (IndexedDB).
    // Organised in folders; each folder's visibility is toggled independently.
    // Also appear as snap targets in route planning mode.
    label: 'User Waypoints',
    cssClass: 'groupUserWaypoints',
    layerIds: ['user-waypoints-circle', 'user-waypoints-label'],
    defaultOn: true,
    section: 'Navigation',
  },
  {
    id: 'terrain',
    // OSM landuse polygons served from PostGIS via Martin tile server.
    // Farmland (cream), wetland (pale blue), residential/commercial/industrial.
    // Fills the gap left by Protomaps landcover which fades out at z11+.
    label: 'Terrain (landuse)',
    cssClass: 'groupTerrain',
    layerIds: ['landuse-fill'],
    defaultOn: true,
    section: 'Terrain',
  },
  {
    id: 'hillshade',
    // Relief shading from Copernicus GLO-30 DEM, raster-dem (Terrarium encoding).
    // Off by default: cosmetic/context layer, not flight-safety-critical, and
    // the heaviest optional tile archive (raster, not vector) — pilots opt in.
    // Redundant with satellite imagery, so also force-hidden in satellite mode
    // (see MapView.tsx basemapMode effect).
    label: 'Hillshade (relief)',
    cssClass: 'groupHillshade',
    layerIds: ['hillshade'],
    defaultOn: false,
    section: 'Terrain',
  },
  {
    id: 'contours',
    // Vector elevation isolines from the same Copernicus GLO-30 DEM as
    // hillshade, generated by scripts/contours_to_pmtiles.sh. Off by
    // default: cosmetic/context layer, not flight-safety-critical.
    // Complements hillshade (relief "feel") with actual readable altitude
    // values — aviation-relevant for terrain-rise awareness near a route.
    label: 'Contour Lines',
    cssClass: 'groupContours',
    layerIds: ['contour-line', 'contour-label'],
    defaultOn: false,
    section: 'Terrain',
  },
  {
    id: 'traffic',
    // ADS-B/MLAT traffic from OpenSky Network (server-side poll, SSE broadcast).
    // Off by default: requires OPENSKY_CLIENT_ID + OPENSKY_CLIENT_SECRET on server.
    // Dead-reckoned client-side at 1 s between 65 s server polls.
    label: 'Air Traffic (ADS-B)',
    cssClass: 'groupTraffic',
    layerIds: ['traffic-urgency-ring', 'traffic-symbols'],
    defaultOn: false,
    section: 'Traffic',
  },
  {
    id: 'wind',
    // Ambient wind-direction/strength arrows sampled across the viewport via
    // Open-Meteo (see @open-vfr/shared/windGrid + useWindGrid.ts) -- a
    // SkyDemon/EasyVFR-style overlay, distinct from AerodromePopup's
    // per-runway favored-end highlight (that one is METAR-driven, single
    // airport; this one is a live grid sample, whole viewport). Off by
    // default: opts the user into extra live fetches on every pan/zoom.
    label: 'Wind Arrows',
    cssClass: 'groupWind',
    layerIds: ['wind-arrows-icon', 'wind-arrows-label'],
    defaultOn: false,
    section: 'Weather',
  },
  {
    id: 'notamCircles',
    // Ad-hoc circles for FIR-wide NOTAMs (restricted/danger areas, navaid
    // outages, military exercise notices) that carry their own
    // coordinates+radius but don't correspond to any charted airspace
    // polygon in the ofm source -- e.g. temporary restricted areas
    // established mid-AIRAC-cycle via AIP supplement. See
    // apps/api/src/notam.ts's getRegionalNotams() and useRegionalNotams.ts.
    label: 'Regional NOTAMs',
    cssClass: 'groupNotamCircles',
    layerIds: ['notam-circles-fill', 'notam-circles-border', 'notam-matched-airspace-fill', 'notam-matched-airspace-border', 'notam-points-cluster', 'notam-points-cluster-count', 'notam-points-unclustered', 'notam-points-label'],
    defaultOn: true,
    section: 'Airspace',
  },
]

// Tiles are served from /public/tiles/ by Vite (dev) and nginx (prod).
// GeoJSON is served as a static file — no PMTiles protocol needed for airspace.
// /tiles/<file> resolves to the current origin so both environments work.

export function getMapStyle(): StyleSpecification {
  return ({
    version: 8,
    // Hosted glyphs/sprites -- via jsDelivr's GitHub CDN mirror rather than
    // raw protomaps.github.io (GitHub Pages) directly. BUG FIX: confirmed
    // live on native (MapLibre Native console error: "Unable to resolve host
    // protomaps.github.io: No address associated with hostname") that raw
    // GitHub Pages hit a transient DNS failure, breaking glyph loading mid-
    // session (garbled/missing map text). jsDelivr serves the identical files
    // from the same open-license repo over a proper global CDN with better
    // DNS/edge reliability. Kept in sync with native's config.ts.
    // TODO: bundle offline copies for Phase 3 (offline-first PWA), and/or
    // fully self-host on tiles.<domain> matching basemap.pmtiles/landuse/
    // hillshade/contours' existing no-external-runtime-dependency pattern.
    glyphs:
      'https://cdn.jsdelivr.net/gh/protomaps/basemaps-assets@main/fonts/{fontstack}/{range}.pbf',
    sprite:
      'https://cdn.jsdelivr.net/gh/protomaps/basemaps-assets@main/sprites/v4/light',
    sources: {
      // Layer 1 — Protomaps OSM basemap (terrain, roads, water, cities)
      protomaps: {
        type: 'vector',
        url: `pmtiles://${versionedTileUrl(TILES_BASE_URL, 'basemap.pmtiles')}`,
        // Tiles extracted at maxzoom=12. MapLibre overzooms vector data
        // automatically so roads/labels stay visible at any zoom level.
        maxzoom: 12,
        attribution:
          '© <a href="https://openstreetmap.org">OpenStreetMap</a> contributors (ODbL)',
      },

      // Layer 2 — OFM airspace polygons (all loaded countries)
      // Retired from Martin/PostGIS -- served as a static file from R2
      // (tiles.openvfr.org), same pattern as openaip-obstacles below.
      // Generated by: scripts/ofmx_to_geojson.py, refreshed by scripts/cron_ofmx.py
      //
      // Properties on each feature:
      //   class  — display class: C D E G R TRA GLDR MODEL
      //   type   — raw OFMX codeType (CTR, TMA, CTA, D, R…)
      //   name   — airspace name (e.g. "STOCKHOLM TMA")
      //   upper  — upper limit string (e.g. "FL095", "3000ft MSL")
      //   lower  — lower limit string (e.g. "SFC", "1500ft AGL")
      //   upper_ft / lower_ft — numeric feet for altitude slider filter
      ofm: {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-airspace.geojson'),
        attribution:
          '© <a href="https://openflightmaps.org">OpenFlightMaps</a> (ODbL)',
      },

      // Layer 3 — OFM aerodrome / heliport points
      // Properties: icao, name, type (AD/HP/AH), elevation_ft, frequencies,
      //             fuel, ppr, ppr_remarks, contacts, runways, towered,
      //             hours_of_operation, handling_facilities,
      //             passenger_facilities (JSONB as text)
      'ofm-aerodromes': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-aerodromes.geojson'),
        attribution:
          '© <a href="https://openflightmaps.org">OpenFlightMaps</a> (ODbL)',
      },

      // Layer 4 — OFM navaids (VOR + NDB)
      // Properties: kind, id, name, navaid_type, freq, freq_str, has_dme, elevation_ft
      'ofm-navaids': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-navaids.geojson'),
        attribution:
          '© <a href="https://openflightmaps.org">OpenFlightMaps</a> (ODbL)',
      },

      // Layer 5 — OFM VFR waypoints (MRP / RP / ENR)
      // Properties: id, name, wp_type, aerodrome
      'ofm-waypoints': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-waypoints.geojson'),
        attribution:
          '© <a href="https://openflightmaps.org">OpenFlightMaps</a> (ODbL)',
      },

      // Layer 6 — Runway centre-line LineStrings
      // Properties: icao, designator, length_m, width_m, surface, mag_brg
      'ofm-runways': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-runways.geojson'),
        attribution:
          '© <a href="https://openflightmaps.org">OpenFlightMaps</a> (ODbL)',
      },

      // Layer 6b — Runway threshold Points (one per runway end)
      // Properties: id (designator e.g. '01L'), icao, mag_brg, true_brg, surface
      'ofm-runway-thresholds': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-runway-thresholds.geojson'),
        attribution:
          '© <a href="https://openflightmaps.org">OpenFlightMaps</a> (ODbL)',
      },

      // Layer 7 — OpenAIP obstacles (wind turbines, towers, chimneys, buildings)
      // Served by Martin from PostGIS obstacles table.
      // Loaded per-country via: scripts/load_obstacles.sh <code>
      //
      // Properties: kind, name, elevation_m, height_m, elevation_ft
      //   kind = wind_turbine | tower | chimney | building | other
      // Retired from Martin/PostGIS -- served as a static file from object
      // storage instead. Small enough (~660 KB for Sweden) that a plain
      // client-side geojson source works fine (unlike landuse, which is too
      // large for this without tiling first). See docs/self-hosting.md.
      'openaip-obstacles': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-obstacles.geojson'),
        attribution:
          '© <a href="https://www.openaip.net">openAIP</a> (CC BY-NC 4.0)',
      },

      // Layer 8 — OSM visual landmarks (churches, masts, windmills, water towers, chimneys)
      // Source: OpenStreetMap via Overpass API — ODbL
      // Generated by: scripts/osm_landmarks_to_geojson.py
      //
      // Properties: kind, name, height_m
      //   kind = church | mast | windmill | water_tower | chimney
      // Note: masts/chimneys and windmills within dedup radii of OpenAIP obstacles
      // are suppressed at data-prep time to avoid double-rendering.
      'osm-landmarks': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-landmarks.geojson'),
        attribution:
          '© <a href="https://openstreetmap.org">OpenStreetMap</a> contributors (ODbL)',
      },

      // Layer 9 — OSM landuse vector tiles (farmland, residential, commercial, industrial)
      // Retired from Postgres/Martin -- static per-country PMTiles from
      // object storage, same pattern as protomaps/basemap.pmtiles above.
      // Raw GeoJSON is ~390 MB (unlike every other retired layer, which is
      // under a few MB), too large for a plain client-side geojson source --
      // tiled with tippecanoe so MapLibre uses HTTP Range Requests instead
      // of one giant download. See docs/self-hosting.md.
      //
      // The Protomaps basemap drops landcover at z11+, leaving farmland and
      // city areas invisible at VFR planning zooms.  This layer fills that gap.
      //
      // Region is swapped at runtime via a full removeSource/addSource swap
      // (MapView.tsx) when the user changes region -- PMTiles vector sources
      // (url-based, not tiles[]-based) have no setTiles() equivalent, unlike
      // the old Martin-backed vector source.
      //
      // Source-layer name: 'landuse'  (matches tippecanoe's -l landuse flag)
      // Properties: kind (farmland|residential|commercial|industrial), country
      'osm-landuse': getLanduseSource(DEFAULT_REGION),
      'osm-hillshade': getHillshadeSource(DEFAULT_REGION),
      'osm-contours': getContoursSource(DEFAULT_REGION),

      // Layer 10 — OSM aeroway lines (taxiways, aprons, OSM runways)
      // Retired from Postgres/Martin -- static per-country GeoJSON from
      // object storage. See docs/self-hosting.md.
      //
      // Taxiways are thin lines that appear at high zoom (z13+) inside aerodromes.
      // They complement the OFM runway centre-lines which only cover labelled runways.
      //
      // Properties: kind (taxiway|apron|runway), name
      'osm-aeroways': {
        type: 'geojson',
        data: versionedTileUrl(TILES_BASE_URL, 'se-aeroways.geojson'),
        attribution:
          '© <a href="https://openstreetmap.org">OpenStreetMap</a> contributors (ODbL)',
      },

      // Layer 11 — Live ADS-B traffic (updated via useTraffic SSE hook).
      // Empty FeatureCollection on init; MapView updates it via setData() every 1 s.
      // Each feature: Point, properties: { icao24, callsign, altFt, speedKts, trackDeg, vertFpm, onGround }
      'traffic': {
        type: 'geojson',
        data: { type: 'FeatureCollection', features: [] },
      },

      // Layer 11b — Ambient wind-arrows overlay (updated via useWindGrid hook).
      // Empty FeatureCollection on init; MapView pushes a coarse grid of
      // Open-Meteo wind samples (see @open-vfr/shared/windGrid) via setData()
      // on moveend while the 'wind' layer group is enabled. Each feature:
      // Point, properties: { dirDeg, speedKts }.
      'wind-grid': {
        type: 'geojson',
        data: { type: 'FeatureCollection', features: [] },
      },

      // Satellite basemap raster — ESRI World Imagery.
      // Hidden by default; shown when the user switches to satellite mode via the
      // runtime API (map.setLayoutProperty).  No style reload needed.
      'satellite-basemap': {
        type: 'raster',
        tiles: SATELLITE_TILES,
        tileSize: 256,
        maxzoom: 19,
        // "Powered by Esri" attribution is required by Esri whenever an ArcGIS
        // service/tile endpoint is used, in addition to the data-source credit
        // below. See https://developers.arcgis.com/documentation/glossary/esri-attribution/
        attribution:
          'Powered by Esri &mdash; Tiles &copy; Esri &mdash; Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community',
      },
    },
    layers: [
      // ── Satellite raster (bottom of stack, hidden by default) ────────────
      // Revealed by MapView when basemapMode === 'satellite'.
      // Must be first so all vector aviation layers render on top.
      {
        id: 'satellite-raster',
        type: 'raster',
        source: 'satellite-basemap',
        layout: { visibility: 'none' },
      },

      // ── Layer 1: Protomaps basemap ───────────────────────────────────────
      // Pass lang:'sv' so the label layers (places_locality, roads_labels_major,
      // water_label_lakes, etc.) are included.  Without a lang the entire label
      // set is silently omitted by @protomaps/basemaps.
      //
      // Override the built-in landcover layer: the default fades farmland /
      // urban_area / grassland colours from opacity 1→0 between zoom 5–7,
      // leaving a bare earth tone at every zoom level pilots actually use.
      //
      // We keep landcover visible at 0.85 from zoom 7 onwards so that
      // farmland (pale yellow-green) and urban_area (light grey) remain
      // readable at all VFR planning zoom levels.  Forest/park areas are
      // re-rendered on top by the landuse_park layer (which fades in at
      // z6–11) so double-rendering of forest is fine and intentional.
      // No detailed landuse replacement layer exists for farmland in the
      // Protomaps LIGHT theme, so we must never fade landcover to 0.
      // ── Layer 1: Protomaps basemap + OSM landuse fill (interleaved) ─────
      // Build the Protomaps layer list, then split it at the first line or
      // symbol layer (boundary between polygon fills and roads/labels).
      // Our landuse-fill is inserted at that split point.
      // Protomaps landcover.farmland color is also patched to ICAO cream here
      // so the z10→z11 handoff from landcover to our OSM layer is seamless.
      ...(() => {
        // ICAO VFR colour conventions:
        //   farmland    → pale cream/yellow  #F2EDC8 — ICAO 1:500k chart standard
        //   residential → warm light grey    rgba(221,214,204)
        //   commercial  → dusty purple-grey  rgba(205,197,222)
        //   industrial  → dusty blue-grey    rgba(184,206,213)
        //   forest/wood → handled by Protomaps landuse_park (#9cd3b4 / #a0d9a0)
        //
        // Yellow on aviation maps = terrain proximity WARNING (dynamic, not landuse).
        // Farmland cream is distinct from forest greens and from terrain-alert amber.
        //
        // residential/commercial/industrial were originally near-white greys
        // (rgba(230,230,230)/(222,220,230)/(209,221,225)) deliberately matched to
        // Protomaps' own urban_area grey for a seamless z10 blend -- but Protomaps
        // drops landcover entirely past z11 (flat grey "void", see landcover
        // fill-opacity interpolation below), and those three colors are also
        // nearly identical to EACH OTHER. Result: toggling this whole layer
        // visually only ever seemed to affect farmland, because residential/
        // commercial/industrial fills were rendering exactly as coded but were
        // indistinguishable from the void and from one another to the eye.
        // Bumped saturation/hue-separation on all three below while keeping them
        // pastel/subtle (aviation-chart-appropriate, not garish).
        const FARMLAND_CREAM = 'rgba(242,237,200,1)'

        const pm = (layers('protomaps', LIGHT, { lang: 'sv' }) as StyleSpecification['layers']).map(
          (layer) => {
            if (layer.id === 'landcover') {
              // Override opacity so landcover stays visible at VFR planning zooms,
              // AND override the farmland fill-color to ICAO cream so the z10→z11
              // handoff to our OSM layer is seamless (no green→cream jump).
              const origPaint = (layer as { paint?: Record<string, unknown> }).paint ?? {}
              const origColor = origPaint['fill-color'] as unknown[]
              // origColor is a 'match' expression: ['match', ['get','kind'], 'grassland', c, ...]
              // Swap the farmland stop (index 8) to ICAO cream.
              const patchedColor = Array.isArray(origColor)
                ? origColor.map((v, i) => {
                    // The element immediately after the 'farmland' string literal is its color value
                    const prev = origColor[i - 1]
                    return typeof prev === 'string' && prev === 'farmland' ? FARMLAND_CREAM : v
                  })
                : origColor
              return {
                ...layer,
                paint: {
                  ...origPaint,
                  'fill-color': patchedColor,
                  'fill-opacity': [
                    'interpolate', ['linear'], ['zoom'],
                    5, 0,
                    7, 0.85,
                    // No upper stop — MapLibre clamps to 0.85 at all higher zooms.
                  ],
                },
              }
            }
            return layer
          },
        )

        // Insert landuse-fill just before the Protomaps 'buildings' fill layer.
        // Protomaps interleaves several fill layers among the road lines:
        //   landuse_runway, water, landuse_pedestrian, landuse_pier, buildings
        // By inserting before 'buildings' (not before the first line):
        //   - Protomaps water (lakes/rivers) renders BELOW our fills →
        //     wetland polygons are visible above lake polygons, not hidden by them
        //   - Buildings render ABOVE our fills → correct urban rendering
        //   - All road lines and labels are also above us ✓
        const buildingsIdx = pm.findIndex((l: { id?: string }) => l.id === 'buildings')
        const insertAt = buildingsIdx !== -1 ? buildingsIdx : pm.length

        // ── OSM landuse fill — farmland / residential / commercial / industrial
        // Farmland uses ICAO cream (same as the patched Protomaps landcover above)
        // for a seamless z10→z11 transition. Forest is never loaded into PostGIS —
        // it is handled entirely by Protomaps landuse_park.
        const landuseFill = {
          id: 'landuse-fill',
          type: 'fill',
          source: 'osm-landuse',
          'source-layer': 'landuse',
          paint: {
            'fill-color': [
              'match', ['get', 'kind'],
              'farmland',    FARMLAND_CREAM,
              'residential', 'rgba(221,214,204,1)',
              'commercial',  'rgba(205,197,222,1)',
              'industrial',  'rgba(184,206,213,1)',
              'wetland',     'rgba(188,220,235,1)',  // pale blue — aviation chart convention
                             'rgba(220,220,220,0)',
            ],
            'fill-opacity': 0.85,
          },
        } as StyleSpecification['layers'][number]

        // ── Runway/taxiway lines: interleave BEFORE basemap symbol layers ──────
        // Protomaps puts all text/symbol layers (road names, place labels) at the
        // end of its 71-layer stack.  If our line layers follow the full Protomaps
        // spread they overdraw those labels.  Insert them just before the first
        // Protomaps symbol layer so basemap text stays on top.
        const firstSymbolIdx = pm.findIndex((l: { type?: string }) => l.type === 'symbol')
        // +1 accounts for landuseFill already being inserted at insertAt (<= firstSymbolIdx)
        const runwayInsertAt = (firstSymbolIdx !== -1 ? firstSymbolIdx : pm.length) + 1

        const withLanduse = [...pm.slice(0, insertAt), landuseFill, ...pm.slice(insertAt)]
        return [
          ...withLanduse.slice(0, runwayInsertAt),
          // ── Taxiways / aprons (OSM, static GeoJSON from R2) ──
          {
            id: 'taxiway-line',
            type: 'line',
            source: 'osm-aeroways',
            minzoom: 13,
            filter: ['in', ['get', 'kind'], ['literal', ['taxiway', 'apron', 'runway']]],
            layout: { 'line-cap': 'round', 'line-join': 'round' },
            paint: {
              'line-color': ['match', ['get', 'kind'],
                'taxiway', '#d4cc8a',
                'apron',   '#c8c8b0',
                '#b0b8c0',
              ],
              'line-width': [
                'interpolate', ['linear'], ['zoom'],
                13, ['match', ['get', 'kind'], 'taxiway', 1, 'apron', 1, 2],
                16, ['match', ['get', 'kind'], 'taxiway', 6, 'apron', 4, 10],
              ],
              'line-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0, 14, 0.85],
            },
          },
          // ── OFM runway centre-lines: grey outline + surface-tinted fill ──
          {
            id: 'runways-outline',
            type: 'line',
            source: 'ofm-runways',
            minzoom: 11,
            layout: { 'line-cap': 'butt' },
            paint: {
              'line-color': RUNWAY_COLORS.outline,
              'line-width': [
                'interpolate', ['exponential', 2], ['zoom'],
                11, ['*', ['/', ['coalesce', ['get', 'width_m'], 30], 30], 1.5],
                14, ['*', ['/', ['coalesce', ['get', 'width_m'], 30], 30], 7],
                17, ['*', ['/', ['coalesce', ['get', 'width_m'], 30], 30], 32],
              ],
              'line-opacity': ['interpolate', ['linear'], ['zoom'], 11, 0, 12, 0.9],
            },
          },
          {
            id: 'runways-line',
            type: 'line',
            source: 'ofm-runways',
            minzoom: 11,
            layout: { 'line-cap': 'butt' },
            paint: {
              'line-color': [
                'match', ['get', 'surface'],
                'ASPH', RUNWAY_COLORS.asphalt,
                'CONC', RUNWAY_COLORS.concrete,
                RUNWAY_COLORS.grass,
              ],
              'line-width': [
                'interpolate', ['exponential', 2], ['zoom'],
                11, ['*', ['/', ['coalesce', ['get', 'width_m'], 30], 30], 1],
                14, ['*', ['/', ['coalesce', ['get', 'width_m'], 30], 30], 5],
                17, ['*', ['/', ['coalesce', ['get', 'width_m'], 30], 30], 24],
              ],
              'line-opacity': ['interpolate', ['linear'], ['zoom'], 11, 0, 12, 1],
            },
          },
          ...withLanduse.slice(runwayInsertAt),
        ] as StyleSpecification['layers']
      })(),

      // ── Relief shading (hillshade) ───────────────────────────────
      // BUG FIX (verified live): originally sat BELOW Protomaps/OSM fills
      // (the 'sits below basemap so translucent fills blend over it' design
      // borrowed from MapTiler Outdoor / OSM hillshade conventions), but
      // landcover/landuse-fill's 0.85 fill-opacity left at most ~15% of
      // this layer's own color reaching the screen — a live A/B test
      // (toggle on vs off, identical screenshots) over genuinely steep,
      // snow-capped Kiruna-area fjell terrain confirmed ZERO visible
      // difference despite tiles loading correctly (real ~126KB Terrarium
      // PNG payloads). Since 'hillshade-exaggeration' is capped at 1.0 by
      // the MapLibre style spec (a first attempt at 2.5 failed the ENTIRE
      // style validation and blanked the whole map — caught immediately
      // via console error during local testing), paint-property tuning
      // alone could not compensate for an 85%-opaque layer on top. Moved
      // here instead — same position as 'contour-line' below, i.e. above
      // ALL basemap fills/roads/labels — which a live test confirmed
      // renders cleanly (contour lines stay fully legible over roads/
      // labels/water at this position, so hillshade does too).
      // Off by default (see LAYER_GROUPS 'hillshade'); toggled via setLayoutProperty.
      // BUG FIX (data pipeline, not style-side anymore): the DEM mosaic used
      // to extend past a country's real border into neighbouring countries/
      // the sea, rendering a stark artificial straight-line rectangle cutoff
      // in hillshade instead of fading out at the actual border. Originally
      // patched here with a hand-generated GeoJSON overlay mask layer for
      // Sweden specifically -- didn't scale to the ~38 countries in REGIONS,
      // each of which would have needed its own manually-generated mask.
      // Fixed properly at the source instead: scripts/dem_mosaic.sh now
      // auto-clips the DEM itself to each country's real border (via
      // scripts/country_mask.sh, Natural Earth boundaries, keyed off the
      // same COUNTRY_CODE the pipeline already has) before hillshade/contours
      // are ever generated -- no style-side masking layer needed at all.
      // BUG FIX (overzoom blockiness at the border, reported live): source
      // real maxzoom is 10 (~90m/px, see getHillshadeSource()'s comment) --
      // MapLibre correctly overzooms (upscales) the z10 tile above that, but
      // each real data pixel then covers more and more screen pixels the
      // further in you zoom, most visible as a hard, blocky/stairstepped
      // dark band tracing the country-border alpha cutoff (fine, smooth
      // real coastline in the source data -- see country_mask.sh's 10m
      // admin-0 dataset -- rendered as a chunky staircase once magnified
      // several zoom levels past the archive's real resolution, not a data
      // bug). A layer-level `maxzoom` stops MapLibre from *rendering* this
      // layer at all beyond that zoom (distinct from the source `maxzoom`
      // above, which only bounds which tile is fetched/overzoomed) -- low-
      // res 90m/px relief isn't meaningfully useful this close in anyway.
      {
        id: 'hillshade',
        type: 'hillshade',
        source: 'osm-hillshade',
        maxzoom: 11,
        layout: { visibility: 'none' },
        paint: {
          'hillshade-exaggeration': 0.5,
          'hillshade-shadow-color': 'rgba(50,35,20,0.75)',
          'hillshade-highlight-color': 'rgba(255,255,255,0.8)',
          'hillshade-accent-color': 'rgba(50,35,20,0.5)',
        },
      },

      // ── Elevation contour lines (Copernicus GLO-30 DEM, vector) ────────
      // Rendered above basemap fills/labels (so isolines aren't buried under
      // farmland/urban colours) but below all aviation overlays (airspace,
      // aerodromes, etc.) so terrain context never competes with flight data.
      // Off by default (see LAYER_GROUPS 'contours'); toggled via setLayoutProperty.
      // BUG FIX (verified live): the original 0.6–1.4px width at 0.55
      // opacity was effectively invisible in practice — real-world test
      // over Kiruna-area fjell terrain (steep, dense real contour data
      // confirmed via direct PMTiles/MVT tile decode: layer 'contours',
      // real elev_m-tagged features) showed no visible lines at any zoom
      // from 0.1 NM to 5 NM. Widened + darkened + upped opacity so lines
      // read clearly against the app's pale/pastel basemap palette.
      {
        id: 'contour-line',
        type: 'line',
        source: 'osm-contours',
        'source-layer': 'contours',
        minzoom: 8,
        layout: { visibility: 'none', 'line-join': 'round' },
        paint: {
          'line-color': 'rgba(120,80,35,0.85)',
          // Index contours (multiples of 250m) drawn wider than intermediate ones.
          'line-width': ['case', ['==', ['%', ['round', ['get', 'elev_m']], 250], 0], 2.2, 1.1],
        },
      },
      {
        id: 'contour-label',
        type: 'symbol',
        source: 'osm-contours',
        'source-layer': 'contours',
        minzoom: 10,
        // Only label index contours (every 250m) to avoid clutter.
        filter: ['==', ['%', ['round', ['get', 'elev_m']], 250], 0],
        layout: {
          visibility: 'none',
          'symbol-placement': 'line',
          'text-field': ['concat', ['to-string', ['round', ['get', 'elev_m']]], 'm'],
          'text-font': ['Noto Sans Regular'],
          'text-size': 10,
        },
        paint: {
          'text-color': 'rgba(120,85,40,0.9)',
          'text-halo-color': 'rgba(255,255,255,0.8)',
          'text-halo-width': 1,
        },
      },

      // ── Layer 2: Class C — CTR + TMA ──────────────────────────────────────
      // Both CTR and TMA are Class C in Sweden. The 'type' property is used
      // in paint expressions to give CTRs stronger styling than TMAs.
      {
        id: 'airspace-fill-c',
        type: 'fill',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'C'],
        paint: {
          'fill-color': [
            'match', ['get', 'type'],
            'CTR', AC.cCtrFill,
                   AC.cTmaFill,
          ],
          'fill-outline-color': AC.transparent,
        },
      },
      // Inset shading band — wide, translucent, offset INTO the polygon interior
      // via positive line-offset. Since the source geometry is Polygon (not
      // LineString), MapLibre's line-offset is winding-order-independent for
      // polygon features: positive = inset (inward), negative = outset
      // (outward) — per the style-spec doc, this is guaranteed regardless of
      // exterior-ring vertex order. This unambiguously shows which side of the
      // boundary the airspace occupies (line-width 7, line-offset 3.5,
      // line-opacity 0.2 using the same colour as the crisp border).
      {
        id: 'airspace-inset-c',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'C'],
        paint: {
          'line-color': [
            'match', ['get', 'type'],
            'CTR', AC.cCtrBorder,
                   AC.cTmaBorder,
          ],
          'line-width': 6,
          'line-offset': 3,
          'line-opacity': 0.22,
        },
      },
      {
        id: 'airspace-border-c',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'C'],
        paint: {
          'line-color': [
            'match', ['get', 'type'],
            'CTR', AC.cCtrBorder,
                   AC.cTmaBorder,
          ],
          'line-width': [
            'match', ['get', 'type'],
            'CTR', 2.0,
            1.4,
          ],
        },
      },
      {
        id: 'airspace-label-c',
        type: 'symbol',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'C'],
        layout: {
          'symbol-placement': 'line',
          'text-offset': [0, 1],
          'text-field': AIRSPACE_LABEL_TEXT_FIELD,
          'text-size': 10,
          'text-justify': 'center',
          'symbol-spacing': 200,
          'text-font': ['Noto Sans Regular'],
        },
        paint: {
          'text-color': [
            'match', ['get', 'type'],
            'CTR', AC.cCtrBorder,
                   AC.cTmaBorder,
          ],
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.2,
        },
      },

      // ── Layer 3: Class D ───────────────────────────────────────────────
      // Includes: Danger areas (type=D), Class D CTRs, Class D TMAs
      {
        id: 'airspace-fill-d',
        type: 'fill',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'D'],
        paint: {
          'fill-color': AC.dFill,
          'fill-outline-color': AC.transparent,
        },
      },
      {
        id: 'airspace-inset-d',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'D'],
        paint: {
          'line-color': AC.dBorder,
          'line-width': 6,
          'line-offset': 3,
          'line-opacity': 0.20,
        },
      },
      {
        id: 'airspace-border-d',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'D'],
        paint: {
          'line-color': AC.dBorder,
          'line-width': 1.2,
          'line-dasharray': [4, 2],
        },
      },
      {
        id: 'airspace-label-d',
        type: 'symbol',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'D'],
        layout: {
          'symbol-placement': 'line',
          'text-offset': [0, 1],
          'text-field': AIRSPACE_LABEL_TEXT_FIELD,
          'text-size': 10,
          'text-justify': 'center',
          'symbol-spacing': 200,
          'text-font': ['Noto Sans Regular'],
        },
        paint: {
          'text-color': AC.dBorder,
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.2,
        },
      },

      // ── Layer 4: Class E ────────────────────────────────────────────────
      {
        id: 'airspace-fill-e',
        type: 'fill',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'E'],
        paint: {
          'fill-color': AC.eFill,
          'fill-outline-color': AC.transparent,
        },
      },
      {
        id: 'airspace-inset-e',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'E'],
        paint: {
          'line-color': AC.eBorder,
          'line-width': 6,
          'line-offset': 3,
          'line-opacity': 0.20,
        },
      },
      {
        id: 'airspace-border-e',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'E'],
        paint: {
          'line-color': AC.eBorder,
          'line-width': 1.5,
          'line-dasharray': [4, 2],
        },
      },
      {
        id: 'airspace-label-e',
        type: 'symbol',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'E'],
        layout: {
          'symbol-placement': 'line',
          'text-offset': [0, 1],
          'text-field': AIRSPACE_LABEL_TEXT_FIELD,
          'text-size': 10,
          'text-justify': 'center',
          'symbol-spacing': 200,
          'text-font': ['Noto Sans Regular'],
        },
        paint: {
          'text-color': AC.eBorder,
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.2,
        },
      },

      // ── Layer 5: Class G (RMZ / ATZ zones) ────────────────────────────
      // Class G in OFM = RMZ (radio mandatory) + ATZ (aerodrome traffic zone)
      // These are specific zones, NOT a country-wide overlay. 28 features.
      {
        id: 'airspace-fill-g',
        type: 'fill',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'G'],
        paint: {
          'fill-color': AC.gFill,
          'fill-outline-color': AC.transparent,
        },
      },
      {
        id: 'airspace-inset-g',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'G'],
        paint: {
          'line-color': AC.gBorder,
          'line-width': 5,
          'line-offset': 2.5,
          'line-opacity': 0.18,
        },
      },
      {
        id: 'airspace-border-g',
        type: 'line',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'G'],
        paint: {
          'line-color': AC.gBorder,
          'line-width': 1.0,
          'line-dasharray': [2, 2],
        },
      },
      {
        id: 'airspace-label-g',
        type: 'symbol',
        source: 'ofm',
        filter: ['==', ['get', 'class'], 'G'],
        layout: {
          'symbol-placement': 'line',
          'text-offset': [0, 1],
          'text-field': AIRSPACE_LABEL_TEXT_FIELD,
          'text-size': 9,
          'text-justify': 'center',
          'symbol-spacing': 200,
          'text-font': ['Noto Sans Regular'],
        },
        paint: {
          'text-color': AC.gBorder,
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.2,
        },
      },

      // ── Layer 6: Restricted (R / TRA) ──────────────────────────────────
      {
        id: 'airspace-fill-restricted',
        type: 'fill',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
        paint: {
          'fill-color': [
            'match', ['get', 'class'],
            'R',   AC.rFill,
            'TRA', AC.traFill,
                   AC.transparent,
          ],
          'fill-outline-color': AC.transparent,
        },
      },
      {
        id: 'airspace-inset-restricted',
        type: 'line',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
        paint: {
          'line-color': [
            'match', ['get', 'class'],
            'R',   AC.rBorder,
            'TRA', AC.traBorder,
                   AC.traBorder,
          ],
          'line-width': 6,
          'line-offset': 3,
          'line-opacity': 0.24,
        },
      },
      {
        id: 'airspace-border-restricted',
        type: 'line',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
        paint: {
          'line-color': [
            'match', ['get', 'class'],
            'R',   AC.rBorder,
            'TRA', AC.traBorder,
                   AC.traBorder,
          ],
          'line-width': [
            'match', ['get', 'class'],
            'R', 1.8,
            1.2,
          ],
        },
      },
      {
        id: 'airspace-label-restricted',
        type: 'symbol',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['R', 'TRA']]],
        layout: {
          'symbol-placement': 'line',
          'text-offset': [0, 1],
          'text-field': AIRSPACE_RESTRICTED_LABEL_TEXT_FIELD,
          'text-size': 10,
          'text-justify': 'center',
          'symbol-spacing': 200,
          'text-font': ['Noto Sans Regular'],
        },
        paint: {
          'text-color': [
            'match', ['get', 'class'],
            'R',   AC.rBorder,
            'TRA', AC.traBorder,
                   AC.traBorder,
          ],
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.2,
        },
      },

      // ── Layer 7: Activity areas (GLDR / MODEL) — default off ──────────────
      {
        id: 'airspace-fill-activity',
        type: 'fill',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
        layout: { visibility: 'none' },
        paint: {
          'fill-color': [
            'match', ['get', 'class'],
            'GLDR',  AC.gldrFill,
            'MODEL', AC.modelFill,
                     AC.transparent,
          ],
          'fill-outline-color': AC.transparent,
        },
      },
      {
        id: 'airspace-inset-activity',
        type: 'line',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
        layout: { visibility: 'none' },
        paint: {
          'line-color': [
            'match', ['get', 'class'],
            'GLDR',  AC.gldrBorder,
            'MODEL', AC.modelBorder,
                     AC.gBorder,
          ],
          'line-width': 5,
          'line-offset': 2.5,
          'line-opacity': 0.16,
        },
      },
      {
        id: 'airspace-border-activity',
        type: 'line',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
        layout: { visibility: 'none' },
        paint: {
          'line-color': [
            'match', ['get', 'class'],
            'GLDR',  AC.gldrBorder,
            'MODEL', AC.modelBorder,
                     AC.gBorder,
          ],
          'line-width': 1.0,
          'line-dasharray': [3, 2],
        },
      },
      {
        id: 'airspace-label-activity',
        type: 'symbol',
        source: 'ofm',
        filter: ['in', ['get', 'class'], ['literal', ['GLDR', 'MODEL']]],
        layout: {
          visibility: 'none',
          'symbol-placement': 'line',
          'text-offset': [0, 1],
          'text-field': AIRSPACE_LABEL_TEXT_FIELD,
          'text-size': 9,
          'text-justify': 'center',
          'symbol-spacing': 200,
          'text-font': ['Noto Sans Regular'],
        },
        paint: {
          'text-color': [
            'match', ['get', 'class'],
            'GLDR',  AC.gldrBorder,
            'MODEL', AC.modelBorder,
                     AC.gBorder,
          ],
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.2,
        },
      },

      // ── Layer 8: VOR navaids ─────────────────────────────────────────────
      // VOR symbol layer — canvas-drawn hexagon compass-rose (nav-vor).
      // Image registered by registerNavaidImages() in MapView's styledata handler.
      {
        id: 'navaids-vor-icon',
        type: 'symbol',
        source: 'ofm-navaids',
        minzoom: 6,
        filter: ['==', ['get', 'kind'], 'VOR'],
        layout: {
          'icon-image': 'nav-vor',
          'icon-size': [
            'interpolate', ['linear'], ['zoom'],
            6, 0.55, 9, 0.75, 13, 1.0,
          ],
          'icon-allow-overlap': true,
          'icon-ignore-placement': false,
        },
      },
      {
        id: 'navaids-vor-label',
        type: 'symbol',
        source: 'ofm-navaids',
        minzoom: 7,
        filter: ['==', ['get', 'kind'], 'VOR'],
        layout: {
          'text-field': [
            'step', ['zoom'],
            ['get', 'id'],            // zoom 7–9: just the identifier
            9, ['concat', ['get', 'id'], '\n', ['get', 'freq_str']],  // zoom 9+: id + freq
          ],
          'text-font': ['Noto Sans Medium'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 7, 9, 12, 11],
          'text-anchor': 'top',
          'text-offset': [0, 1.0],
          'text-allow-overlap': false,
          'text-line-height': 1.2,
        },
        paint: {
          'text-color': NAVAID_COLORS.vorText,
          'text-halo-color': NAVAID_COLORS.halo,
          'text-halo-width': 1.5,
        },
      },

      // ── Layer 9: NDB navaids ─────────────────────────────────────────────
      // NDB symbol layer — canvas-drawn double-circle (nav-ndb).
      {
        id: 'navaids-ndb-icon',
        type: 'symbol',
        source: 'ofm-navaids',
        minzoom: 6,
        filter: ['==', ['get', 'kind'], 'NDB'],
        layout: {
          'icon-image': 'nav-ndb',
          'icon-size': [
            'interpolate', ['linear'], ['zoom'],
            6, 0.50, 9, 0.70, 13, 0.90,
          ],
          'icon-allow-overlap': true,
          'icon-ignore-placement': false,
        },
      },
      {
        id: 'navaids-ndb-label',
        type: 'symbol',
        source: 'ofm-navaids',
        minzoom: 8,
        filter: ['==', ['get', 'kind'], 'NDB'],
        layout: {
          'text-field': [
            'step', ['zoom'],
            ['get', 'id'],
            9, ['concat', ['get', 'id'], '\n', ['get', 'freq_str']],
          ],
          'text-font': ['Noto Sans Regular'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 8, 9, 12, 11],
          'text-anchor': 'top',
          'text-offset': [0, 0.9],
          'text-allow-overlap': false,
          'text-line-height': 1.2,
        },
        paint: {
          'text-color': NAVAID_COLORS.ndbText,
          'text-halo-color': NAVAID_COLORS.halo,
          'text-halo-width': 1.5,
        },
      },

      // ── Layer 10: VFR MRP (Mandatory Reporting Points) ───────────────────
      // MRP symbol layer — canvas-drawn filled triangle (wp-mrp).
      {
        id: 'waypoints-mrp-icon',
        type: 'symbol',
        source: 'ofm-waypoints',
        minzoom: 8,
        filter: ['==', ['get', 'wp_type'], 'MRP'],
        layout: {
          'icon-image': 'wp-mrp',
          'icon-size': [
            'interpolate', ['linear'], ['zoom'],
            8, 0.50, 12, 0.75,
          ],
          'icon-allow-overlap': true,
          'icon-ignore-placement': false,
        },
      },
      {
        id: 'waypoints-mrp-label',
        type: 'symbol',
        source: 'ofm-waypoints',
        minzoom: 9,
        filter: ['==', ['get', 'wp_type'], 'MRP'],
        layout: {
          'text-field': ['get', 'id'],
          'text-font': ['Noto Sans Regular'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 9, 9, 12, 11],
          'text-anchor': 'top',
          'text-offset': [0, 0.9],
          'text-allow-overlap': false,
        },
        paint: {
          'text-color': WAYPOINT_COLORS.mrpText,
          'text-halo-color': WAYPOINT_COLORS.halo,
          'text-halo-width': 1.5,
        },
      },

      // ── Layer 11: VFR RP (Reporting Points) — default off ────────────────
      // RP symbol layer — canvas-drawn outline triangle (wp-rp).
      {
        id: 'waypoints-rp-icon',
        type: 'symbol',
        source: 'ofm-waypoints',
        minzoom: 9,
        filter: ['in', ['get', 'wp_type'], ['literal', ['RP', 'ENR', 'ICAO']]],
        layout: {
          visibility: 'none',
          'icon-image': 'wp-rp',
          'icon-size': [
            'interpolate', ['linear'], ['zoom'],
            9, 0.45, 12, 0.70,
          ],
          'icon-allow-overlap': true,
          'icon-ignore-placement': false,
        },
      },
      {
        id: 'waypoints-rp-label',
        type: 'symbol',
        source: 'ofm-waypoints',
        minzoom: 10,
        filter: ['in', ['get', 'wp_type'], ['literal', ['RP', 'ENR', 'ICAO']]],
        layout: {
          visibility: 'none',
          'text-field': ['get', 'id'],
          'text-font': ['Noto Sans Regular'],
          'text-size': 9,
          'text-anchor': 'top',
          'text-offset': [0, 0.9],
          'text-allow-overlap': false,
        },
        paint: {
          'text-color': WAYPOINT_COLORS.rpText,
          'text-halo-color': WAYPOINT_COLORS.halo,
          'text-halo-width': 1.5,
        },
      },

      // ── Runway threshold designator labels ────────────────────────────────
      // One symbol per runway end.  Text is the individual designator ("01L").
      // Rotated by mag_brg so it aligns with (and reads along) the runway heading.
      // Offset pushes the label onto the painted surface rather than on top of the
      // threshold point (which sits at the very end of the runway).
      {
        id: 'runway-threshold-label',
        type: 'symbol',
        source: 'ofm-runway-thresholds',
        minzoom: 12,
        layout: {
          'text-field': ['get', 'id'],
          'text-font': ['Noto Sans Medium'],
          'text-size': RUNWAY_LABEL_DEFAULT_SIZE as ExpressionSpecification,
          // mag_brg is a "not yet computed" placeholder `0` for a large
          // fraction of thresholds in the source data (true_brg is always
          // populated) -- coalesce alone doesn't catch that (only null/undefined
          // substitute), so this falls back to true_brg whenever mag_brg is
          // exactly 0. See @open-vfr/shared/runwayWind's effectiveMagBrg,
          // which every JS-side reader of this same field goes through.
          'text-rotate': [
            'case',
            ['==', ['coalesce', ['get', 'mag_brg'], 0], 0],
            ['coalesce', ['get', 'true_brg'], 0],
            ['get', 'mag_brg'],
          ] as unknown as ExpressionSpecification,
          'text-rotation-alignment': 'map',
          'text-pitch-alignment': 'map',
          'text-allow-overlap': true,
          'text-ignore-placement': true,
        },
        paint: {
          'text-color': RUNWAY_LABEL_DEFAULT_COLOR,
          'text-halo-color': RUNWAY_LABEL_DEFAULT_HALO,
          'text-halo-width': 1.5,
          'text-opacity': RUNWAY_LABEL_DEFAULT_OPACITY as ExpressionSpecification,
        },
      },

      // ── Taxiway designator letters (OSM name tag: "A", "Bravo", etc.) ──────
      // Placed repeating along the line (symbol-placement:'line') now that the
      // source is the raw static LineString GeoJSON rather than a server-
      // precomputed centroid-point MVT layer -- same technique as the airspace
      // on-map class/altitude labels (see AGENTS.md gotcha for symbol-placement
      // on line/polygon geometry). Only shown when the OSM feature has a
      // non-empty name.
      {
        id: 'taxiway-label',
        type: 'symbol',
        source: 'osm-aeroways',
        minzoom: 14,
        filter: ['all', ['==', ['get', 'kind'], 'taxiway'], ['!=', ['get', 'name'], '']],
        layout: {
          'symbol-placement': 'line',
          'text-field': ['get', 'name'],
          'text-font': ['Noto Sans Medium'],
          'text-size': ['interpolate', ['linear'], ['zoom'], 14, 9, 17, 12],
          'text-allow-overlap': true,
          'text-ignore-placement': true,
        },
        paint: {
          'text-color': '#5a4e1a',
          'text-halo-color': '#fffce0',
          'text-halo-width': 1.5,
        },
      },

      // ── Layer 11b: Towered-airport ATC status ring ────────────────────────
      // Drawn UNDER the icon symbol layer (declared before it) so the icon
      // paints on top and the ring reads as a halo around it. Only towered
      // airports get a ring at all (filter below) — untowered/AFIS fields are
      // unaffected. Color is a per-ICAO 'match' expression kept in sync by
      // MapView's 60s-interval effect (recomputed from
      // AIP-schedule hours_of_operation, see @open-vfr/shared/atcStatus) via
      // setPaintProperty — never baked in statically here, since open/closed
      // is time-varying and this static style object is not. Starts as the
      // 'unknown' (grey) color for everyone until the first computation runs.
      {
        id: 'aerodromes-atc-ring',
        type: 'circle',
        source: 'ofm-aerodromes',
        filter: ['==', ['get', 'towered'], true],
        paint: {
          'circle-radius': [
            'interpolate', ['linear'], ['zoom'],
            6, 7,
            10, 10,
            13, 13,
          ],
          'circle-color': 'rgba(0,0,0,0)',
          'circle-stroke-width': 2,
          'circle-stroke-color': AERODROME_COLORS.atcUnknown,
        },
      },

      // ── Layer 12: Aerodrome symbols ───────────────────────────────────────
      // Symbol layer using canvas-drawn icons registered by registerAerodromeImages()
      // in MapView's styledata handler.  Icons drawn at 2× for HiDPI.
      //
      // Image IDs (defined in src/utils/aerodromeIcons.ts):
      //   ad-airport   Blue circle + crosshair  — AD and AH types
      //   ad-heliport  Purple circle + H        — HP type
      {
        id: 'aerodromes-icon',
        type: 'symbol',
        source: 'ofm-aerodromes',
        layout: {
          'icon-image': [
            'match', ['get', 'type'],
            'HP', 'ad-heliport',
                  'ad-airport',   // AD, AH, and any unknown type
          ],
          'icon-size': [
            'interpolate', ['linear'], ['zoom'],
            6, 0.45,
            10, 0.65,
            13, 0.85,
          ],
          'icon-allow-overlap': true,
          'icon-ignore-placement': false,
        },
      },

      // ── Layer 12b: Aerodrome ICAO labels ──────────────────────────────────
      {
        id: 'aerodromes-label',
        type: 'symbol',
        source: 'ofm-aerodromes',
        minzoom: 8,
        layout: {
          'text-field': ['get', 'icao'],
          'text-font': ['Noto Sans Medium'],
          'text-size': [
            'interpolate', ['linear'], ['zoom'],
            8, 9, 12, 12,
          ],
          'text-anchor': 'top',
          'text-offset': [0, 1.0],
          'text-allow-overlap': false,
          'text-ignore-placement': false,
        },
        paint: {
          'text-color': AERODROME_COLORS.label,
          'text-halo-color': AERODROME_COLORS.halo,
          'text-halo-width': 1.5,
        },
      },

      // ── Layer 12c: Towered-airport NOTAM hint badge ────────────────────────
      // Small glyph badge (⚠ ATC/tower-related, ⏰ hours-changed, or both)
      // next to a towered airport's icon when an active NOTAM's free text
      // matches a conservative keyword heuristic (see
      // @open-vfr/shared/atcStatus's isNotamAtcRelated/
      // isNotamHoursChangeRelated). Text-only signal, same as the popup's
      // equivalent hint lines -- NEVER affects 'aerodromes-atc-ring's color.
      // filter/text-field kept empty until MapView's periodic effect
      // populates them from GET /api/notam/aerodrome-texts (auth-gated,
      // skipped entirely while signed out).
      {
        id: 'aerodromes-notam-hint',
        type: 'symbol',
        source: 'ofm-aerodromes',
        minzoom: 7,
        filter: ['in', ['get', 'icao'], ['literal', []]],
        layout: {
          'text-field': '',
          'text-font': ['Noto Sans Medium'],
          'text-size': 13,
          'text-anchor': 'bottom-left',
          'text-offset': [0.6, -0.6],
          'text-allow-overlap': true,
          'text-ignore-placement': true,
        },
        paint: {
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.5,
        },
      },

      // ── Layer 13: Obstacles (wind turbines, towers, chimneys) ─────────────
      // Symbol layer using canvas-drawn icons registered by registerObstacleImages()
      // in MapView's styledata handler. Icons are rendered at 2× for HiDPI.
      // Shown from zoom 9 — 3 600+ features means we suppress them at overview
      // zoom levels where they'd form an indistinct mass across Sweden.
      //
      // Image IDs (defined in src/utils/obstacleIcons.ts):
      //   obs-wind-turbine  obs-tower  obs-chimney  obs-building  obs-water-tower  obs-other
      {
        id: 'obstacles-circle',
        type: 'symbol',
        source: 'openaip-obstacles',
        minzoom: 9,
        layout: {
          'icon-image': [
            'match', ['get', 'kind'],
            'wind_turbine', 'obs-wind-turbine',
            'tower',        'obs-tower',
            'chimney',      'obs-chimney',
            'building',     'obs-building',
            'water_tower',  'obs-water-tower',
                            'obs-other',
          ],
          // Scale icons with zoom; at z9 they're small dots, at z14 full-size.
          'icon-size': [
            'interpolate', ['linear'], ['zoom'],
            9, 0.40,
            11, 0.60,
            13, 0.80,
            15, 1.00,
          ],
          'icon-allow-overlap': true,
          'icon-padding': 0,
          'icon-anchor': 'center',
        },
      },

      // ── Layer 13b: Obstacle elevation labels (zoom 12+) ───────────────────
      // Show elevation in feet (AMSL) — the number pilots need for obstacle
      // clearance planning. Only rendered at high zoom to keep the map clean.
      {
        id: 'obstacles-label',
        type: 'symbol',
        source: 'openaip-obstacles',
        minzoom: 12,
        layout: {
          'text-field': ['concat', ['to-string', ['get', 'elevation_ft']], "'"],
          'text-font': ['Noto Sans Regular'],
          'text-size': 9,
          'text-anchor': 'top',
          'text-offset': [0, 0.5],
          'text-allow-overlap': false,
        },
        paint: {
          'text-color': [
            'match', ['get', 'kind'],
            'wind_turbine', OBSTACLE_COLORS.windTurbine,
            'tower',        OBSTACLE_COLORS.tower,
            'chimney',      OBSTACLE_COLORS.chimney,
            'building',     OBSTACLE_COLORS.building,
            'water_tower',  OBSTACLE_COLORS.waterTower,
                            OBSTACLE_COLORS.default,
          ],
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.5,
        },
      },

      // ── Layer 14: OSM landmark icons (churches, masts, windmills…) ─────────
      // Symbol layer using canvas-drawn icons registered by registerLandmarkImages()
      // in MapView's styledata handler. Off by default — toggled via LayerPanel.
      //
      // Image IDs (defined in src/utils/landmarkIcons.ts):
      //   lmk-church  lmk-mast  lmk-windmill  lmk-water-tower  lmk-chimney
      {
        id: 'landmarks-icon',
        type: 'symbol',
        source: 'osm-landmarks',
        minzoom: 10,
        layout: {
          visibility: 'none',
          'icon-image': [
            'match', ['get', 'kind'],
            'church',      'lmk-church',
            'mast',        'lmk-mast',
            'windmill',    'lmk-windmill',
            'water_tower', 'lmk-water-tower',
            'chimney',     'lmk-chimney',
                           'lmk-church',  // fallback (should not occur)
          ],
          // Scale icons from small dots at z10 to full-size at z16.
          'icon-size': [
            'interpolate', ['linear'], ['zoom'],
            10, 0.35,
            12, 0.55,
            14, 0.80,
            16, 1.00,
          ],
          'icon-allow-overlap': false,
          'icon-padding': 2,
          'icon-anchor': 'center',
        },
      },

      // ── Layer 14b: OSM landmark name labels (zoom 13+) ─────────────────────
      // Only shown for features that have a non-empty OSM name tag.
      {
        id: 'landmarks-label',
        type: 'symbol',
        source: 'osm-landmarks',
        minzoom: 13,
        filter: ['!=', ['get', 'name'], ''],
        layout: {
          visibility: 'none',
          'text-field': ['get', 'name'],
          'text-font': ['Noto Sans Regular'],
          'text-size': [
            'interpolate', ['linear'], ['zoom'],
            13, 9,
            16, 11,
          ],
          'text-anchor': 'top',
          'text-offset': [0, 0.6],
          'text-allow-overlap': false,
          'text-optional': true,
        },
        paint: {
          'text-color': [
            'match', ['get', 'kind'],
            'church',      '#455a64',
            'mast',        '#e65100',
            'windmill',    '#5d4037',
            'water_tower', '#00695c',
            'chimney',     '#bf360c',
                           '#455a64',
          ],
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.5,
        },
      },

      // ── Traffic urgency ring (coloured backdrop per proximity level) ────
      // urgency=0 white/distant, 1=green/close, 2=yellow/nearby, 3=red/proximate
      {
        id: 'traffic-urgency-ring',
        type: 'circle',
        source: 'traffic',
        filter: ['!=', ['get', 'onGround'], true],
        layout: { visibility: 'none' },
        paint: {
          'circle-radius': 11,
          'circle-color': [
            'match', ['get', 'urgency'],
            1, '#22c55e',   // green  — close   (< 3 NM / < 3000 ft)
            2, '#eab308',   // yellow — nearby  (< 2 NM / < 1000 ft)
            3, '#ef4444',   // red    — proximate (< 1 NM / < 500 ft)
            'transparent',  // 0 = distant
          ],
          'circle-opacity': [
            'match', ['get', 'urgency'],
            0, 0,
            0.35,
          ],
          'circle-stroke-color': [
            'match', ['get', 'urgency'],
            1, '#22c55e',
            2, '#eab308',
            3, '#ef4444',
            'transparent',
          ],
          'circle-stroke-width': 1.5,
          'circle-stroke-opacity': [
            'match', ['get', 'urgency'],
            0, 0,
            0.8,
          ],
        },
      },

      // ── Traffic symbols (ADS-B / MLAT via OpenSky) ──────────────────────
      // Data updated every 1 s by useTraffic dead-reckoning loop in MapView.
      // Off by default — turned on via LayerPanel toggle.
      // Icon 'traffic-chevron' is registered in MapView styledata handler.
      {
        id: 'traffic-symbols',
        type: 'symbol',
        source: 'traffic',
        filter: ['!=', ['get', 'onGround'], true],
        layout: {
          visibility: 'none',
          // iconId is pre-computed in MapView using selectTrafficIcon()
          // (category + speed → specific silhouette). Falls back to a0.
          'icon-image': ['coalesce', ['get', 'iconId'], 'traffic-icon-a0'],
          'icon-size': 1,
          'icon-rotate': ['get', 'trackDeg'],
          'icon-rotation-alignment': 'map',
          'icon-allow-overlap': true,
          'icon-ignore-placement': true,
          'text-field': [
            'concat',
            ['coalesce', ['get', 'callsign'], ['get', 'icao24']],
            // Only show relative altitude when ownship GPS is available (property absent otherwise)
            ['case',
              ['!', ['has', 'relAltFt']], '',
              ['>', ['get', 'relAltFt'], 0],
              ['concat', '\n+', ['to-string', ['/', ['round', ['/', ['get', 'relAltFt'], 100]], 10]]],
              ['concat', '\n', ['to-string', ['/', ['round', ['/', ['get', 'relAltFt'], 100]], 10]]],
            ],
          ],
          'text-font': ['Noto Sans Medium'],
          'text-size': 10,
          'text-anchor': 'left',
          'text-offset': [1.2, 0],
          'text-allow-overlap': true,
          'text-ignore-placement': true,
          'text-optional': true,
        },
        paint: {
          'icon-opacity': 0.9,
          'text-color': '#ffffff',
          'text-halo-color': '#1e293b',
          'text-halo-width': 1.5,
        },
      },

      // ── Ambient wind-arrows overlay ────────────────────────────────
      // SkyDemon/EasyVFR/synoptic-chart-style wind barbs sampled across the
      // viewport (see useWindGrid.ts). Off by default (LAYER_GROUPS 'wind') --
      // opt-in since it drives extra live Open-Meteo fetches on every pan/zoom.
      // Icons 'wind-barb-{0,5,10,...,100}' registered on demand by
      // registerWindBarbIcon() (MapView styleimagemissing handler); the id
      // expression below rounds speedKts to the nearest 5kt bucket that
      // registration function knows about (@open-vfr/shared/windBarb).
      //
      // Rotation: dirDeg is the meteorological "wind FROM" bearing. Unlike
      // the in-flight wind gauge's arrow (which rotates by dirDeg+180 to
      // point where the air is going), a wind barb's shaft points in the
      // FROM direction by international convention -- pilots already read
      // synoptic-chart barbs this way, so rotating by dirDeg directly (no
      // +180) keeps map barbs consistent with that standard, not the gauge.
      {
        id: 'wind-arrows-icon',
        type: 'symbol',
        source: 'wind-grid',
        layout: {
          visibility: 'none',
          'icon-image': [
            'concat', 'wind-barb-',
            ['to-string', ['max', 0, ['min', 100,
              ['*', ['round', ['/', ['get', 'speedKts'], 5]], 5],
            ]]],
          ],
          'icon-rotate': ['get', 'dirDeg'],
          'icon-rotation-alignment': 'map',
          'icon-anchor': 'bottom',
          // 2026-09-13 UX feedback shrunk this to 0.4-0.8/opacity 0.55 to
          // stop barbs dominating the map -- overcorrected, they became
          // nearly invisible (only the numeric label, with its own white
          // halo, stayed legible). Restored to a readable size; the "don't
          // dominate" goal is now handled by speed-tiered colour
          // (windBarbColorForSpeed: blue/green/amber) rather than by
          // making every barb equally hard to see regardless of strength.
          'icon-size': ['interpolate', ['linear'], ['zoom'], 5, 0.55, 10, 0.85, 14, 1.1],
          'icon-allow-overlap': true,
          'icon-ignore-placement': true,
        },
        paint: {
          'icon-opacity': 0.9,
        },
      },
      {
        id: 'wind-arrows-label',
        type: 'symbol',
        source: 'wind-grid',
        minzoom: 7,
        layout: {
          visibility: 'none',
          'text-field': ['concat', ['to-string', ['get', 'speedKts']], 'kt'],
          'text-font': ['Noto Sans Regular'],
          'text-size': 8,
          'text-anchor': 'top',
          'text-offset': [0, 0.3],
          'text-allow-overlap': false,
          'text-optional': true,
        },
        paint: {
          'text-color': WIND_BARB_COLOR,
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.2,
          'text-opacity': 0.75,
        },
      },
    ],
  }) as unknown as StyleSpecification
}
