/**
 * src/utils/trafficIcons.ts (native)
 *
 * Icon selection for the live traffic layer — port of web's
 * apps/web/src/utils/trafficIcons.ts selectTrafficIcon(), kept in exact
 * sync (same switch, same thresholds, same icon ids) so a target picks the
 * identical silhouette on both platforms. Native can't recolor SVGs at
 * runtime like web's canvas-based registerTrafficIcons() (see AGENTS.md's
 * wind-barb-icon gotcha — same constraint applies here): the actual images
 * are pre-rasterized PNGs generated by scripts/gen-aircraft-icons.mjs and
 * registered via AviationMap.tsx's <Images> block. This file only owns the
 * category+speed → iconId decision, not image loading.
 *
 * Icon selection uses ADS-B emitter category + ground speed together so
 * targets get a distinctive silhouette rather than only a weight-class
 * shape — see web's trafficIcons.ts header comment for the full table.
 *
 * OGN/FLARM targets are mapped onto this SAME category enum before they
 * ever reach this function (apps/api/src/ognTraffic.ts's
 * FLARM_TYPE_TO_CATEGORY) — a glider is category 8 whether OpenSky or OGN
 * reported it, so this file needs zero source-aware branching.
 */

/** All icon ids this function can return. Mirrors web's TRAFFIC_ICON_ENTRIES ids (minus the SVG paths — native loads pre-rasterized PNGs instead, see gen-aircraft-icons.mjs). */
export const TRAFFIC_ICON_IDS = [
  'traffic-icon-a0',
  'traffic-icon-a7',
  'traffic-icon-b1',
  'traffic-icon-b2',
  'traffic-icon-b3',
  'traffic-icon-b4',
  'traffic-icon-c0',
  'traffic-icon-cessna',
  'traffic-icon-learjet',
  'traffic-icon-dh8a',
  'traffic-icon-crjx',
  'traffic-icon-a320',
  'traffic-icon-b737',
  'traffic-icon-b747',
  'traffic-icon-a380',
  'traffic-icon-f15',
] as const

/** Fallback image id used when the category is unknown or unmapped. */
export const TRAFFIC_ICON_FALLBACK = 'traffic-icon-a0'

/**
 * Pick the best silhouette icon for a traffic target.
 * Called in useTraffic.ts when building the GeoJSON feature set; result
 * stored as the `iconId` property so AviationMap's symbol layer can use
 * `['get', 'iconId']`.
 */
export function selectTrafficIcon(
  category: number | null,
  speedKts: number,
): string {
  const cat = category ?? 0
  switch (cat) {
    // ── Special categories — silhouette determined solely by category ─────
    case 7:  return 'traffic-icon-a7'      // rotorcraft
    case 8:  return 'traffic-icon-b1'      // glider
    case 9:  return 'traffic-icon-b2'      // lighter-than-air
    case 10: return 'traffic-icon-b3'      // parachutist
    case 11:
    case 12: return 'traffic-icon-b4'      // ultralight
    case 13: return 'traffic-icon-c0'      // UAV / drone

    // ── Fixed-wing silhouettes (category + speed) ─────────────────────────
    case 1:  // light < 15 500 lbs
      return speedKts >= 250 ? 'traffic-icon-learjet' : 'traffic-icon-cessna'

    case 2:  // small 15 500–75 000 lbs
      if (speedKts >= 320) return 'traffic-icon-crjx'
      if (speedKts >= 200) return 'traffic-icon-dh8a'
      return 'traffic-icon-cessna'

    case 3:  // large 75 000–300 000 lbs
      if (speedKts >= 400) return 'traffic-icon-b737'
      if (speedKts >= 280) return 'traffic-icon-a320'
      return 'traffic-icon-dh8a'

    case 4:  // high-vortex large (B757-class)
      return 'traffic-icon-b737'

    case 5:  // heavy > 300 000 lbs
      return speedKts >= 480 ? 'traffic-icon-a380' : 'traffic-icon-b747'

    case 6:  // high performance (military)
      return 'traffic-icon-f15'

    default: {
      // Cat 0 (no info) + cat 14–19 (reserved/surface/space) — fall back to speed
      if (speedKts >= 450) return 'traffic-icon-b747'
      if (speedKts >= 300) return 'traffic-icon-a320'
      if (speedKts >= 150) return 'traffic-icon-dh8a'
      if (speedKts >= 30)  return 'traffic-icon-cessna'
      return 'traffic-icon-a0'
    }
  }
}
