/**
 * withMapLibreHttpGuard — Expo config plugin that installs a guarded OkHttp
 * client into MapLibre Native's Android HTTP layer, refusing any response
 * that would be read whole into the Java heap when it clearly shouldn't be.
 *
 * WHY (found via a live heap dump, see AGENTS.md "PMTiles range requests
 * must never be answered with the whole archive"): MapLibre's own
 * `HttpRequestImpl$OkHttpCallback.onResponse` accepts any 2xx (`isSuccessful()`)
 * and then calls `ResponseBody.bytes()`, slurping the ENTIRE body into a
 * byte[] with no size check and no "did my Range request actually get a 206"
 * check. PMTiles works purely through tiny Range requests against one big
 * archive; if the origin ever answers a Range request with `200` + the full
 * file instead of `206` + the slice (observed intermittently for the 668 MB
 * basemap.pmtiles), MapLibre buffers the whole archive: the Java heap climbs
 * from ~30 MB straight to the 512 MB largeHeap ceiling in ~15 s and the app
 * throws OutOfMemoryError on the OkHttp thread. That is the crash
 * withAndroidLargeHeap was raising the ceiling for -- raising it just moved
 * the crash from a 256 MB body to a 512 MB one.
 *
 * MapLibre exposes `HttpRequestUtil.setOkHttpClient(Call.Factory)` for
 * exactly this kind of customisation. The replacement client keeps MapLibre's
 * own dispatcher settings (maxRequestsPerHost = 20, read from the 13.6.1
 * bytecode) and adds one interceptor that fails the request -- BEFORE the
 * body is read -- when:
 *   1. the request carried a `Range` header but the response is not 206, or
 *   2. `Content-Length` exceeds MAX_BODY_BYTES, or
 *   3. (no Content-Length / chunked) the body grows past MAX_BODY_BYTES
 *      while being read.
 * A thrown IOException lands in MapLibre's normal `onFailure` path, which it
 * already treats as a transient network error and retries -- the same thing
 * it does for a dropped packet. Nothing else about MapLibre's requests
 * changes: User-Agent, Range, If-None-Match, If-Modified-Since are all added
 * per request by MapLibre itself and pass through untouched.
 *
 * Two mods: a Kotlin source file dropped into the app's package
 * (withDangerousMod -- there is no config-plugin API for "add a source file",
 * this is the documented way), and a one-line install call in
 * MainApplication.onCreate (withMainApplication). Both idempotent.
 */
const { withMainApplication, withDangerousMod, withAppBuildGradle } = require('@expo/config-plugins')
const fs = require('fs')
const path = require('path')

const CLASS_NAME = 'MapLibreHttpGuard'

/**
 * The MapLibre Android SDK is an `implementation` dependency of
 * @maplibre/maplibre-react-native, so it is on the app's RUNTIME classpath
 * but not its COMPILE classpath -- Kotlin in the app module cannot see
 * HttpRequestUtil without a `compileOnly` on the same artifact (compile-time
 * visibility only; no second copy ships). Variant + version are read from the
 * RN module's own android/gradle.properties (the same defaults its
 * build.gradle uses via getConfigurableExtOrDefault) so they cannot drift
 * from what actually ships. A mismatch would be a silent runtime
 * NoSuchMethodError, so a read failure is fatal, not a fallback.
 */
function readMapLibreNativeCoords(projectRoot) {
  const pkgJson = require.resolve('@maplibre/maplibre-react-native/package.json', { paths: [projectRoot] })
  const props = fs.readFileSync(path.join(path.dirname(pkgJson), 'android', 'gradle.properties'), 'utf8')
  const get = (k) => {
    const m = props.match(new RegExp(`^org\\.maplibre\\.reactnative\\.${k}=(.+)$`, 'm'))
    if (!m) throw new Error(`withMapLibreHttpGuard: org.maplibre.reactnative.${k} not found in maplibre-react-native gradle.properties`)
    return m[1].trim()
  }
  return { variant: get('nativeVariant'), version: get('nativeVersion') }
}

function kotlinSource(pkg) {
  return `package ${pkg}

import okhttp3.Dispatcher
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import okhttp3.Response
import okhttp3.ResponseBody.Companion.asResponseBody
import okio.Buffer
import okio.ForwardingSource
import okio.buffer
import android.content.Context
import org.maplibre.android.MapLibre
import org.maplibre.android.module.http.HttpRequestUtil
import java.io.IOException

/**
 * Guarded OkHttp client for MapLibre Native. See plugins/withMapLibreHttpGuard.js
 * (the generator of this file) for the full rationale. Do not edit here --
 * this file is regenerated by \`expo prebuild\`.
 */
object ${CLASS_NAME} {
  /** Largest single response MapLibre may read into memory. PMTiles range
   *  slices are tens of KB; styles/sprites/glyphs/vector tiles are well under
   *  a few MB. Anything bigger is not a tile, it is a bug (or a whole-archive
   *  response) and must not reach ResponseBody.bytes(). */
  private const val MAX_BODY_BYTES = 32L * 1024 * 1024

  @JvmStatic
  fun install(context: Context) {
    // setOkHttpClient() class-loads HttpRequestImpl, whose static initializer
    // builds the User-Agent via MapLibre.getApplicationContext() -- which
    // throws MapLibreConfigurationException until MapLibre.getInstance() has
    // run. The RN module only calls that when the first map view mounts,
    // long after Application.onCreate. Same single-arg call the RN module
    // makes (MLRNMapViewModule.kt); synchronized + idempotent, so its later
    // call is a no-op.
    MapLibre.getInstance(context.applicationContext)
    val dispatcher = Dispatcher().apply { maxRequestsPerHost = 20 }
    val client = OkHttpClient.Builder()
      .dispatcher(dispatcher)
      .addInterceptor(GuardInterceptor())
      .build()
    HttpRequestUtil.setOkHttpClient(client)
  }

  private class GuardInterceptor : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
      val request = chain.request()
      val response = chain.proceed(request)
      val range = request.header("Range")

      // 1. Range request answered with the whole resource instead of a slice.
      if (range != null && response.code != 206 && response.isSuccessful) {
        val len = response.header("Content-Length") ?: "?"
        response.close()
        throw IOException(
          "MapLibreHttpGuard: Range request ($range) answered with HTTP " +
          "\${response.code} (Content-Length \$len) instead of 206 -- refusing to " +
          "buffer the whole resource: \${request.url}"
        )
      }

      // 2. Declared size over the cap.
      val declared = response.header("Content-Length")?.toLongOrNull()
      if (declared != null && declared > MAX_BODY_BYTES) {
        response.close()
        throw IOException(
          "MapLibreHttpGuard: Content-Length \$declared exceeds " +
          "\$MAX_BODY_BYTES bytes: \${request.url}"
        )
      }

      // 3. Unknown size: cap while streaming.
      val body = response.body ?: return response
      if (declared != null) return response
      val capped = object : ForwardingSource(body.source()) {
        var total = 0L
        override fun read(sink: Buffer, byteCount: Long): Long {
          val n = super.read(sink, byteCount)
          if (n > 0) {
            total += n
            if (total > MAX_BODY_BYTES) {
              throw IOException(
                "MapLibreHttpGuard: streamed body exceeded \$MAX_BODY_BYTES bytes: \${request.url}"
              )
            }
          }
          return n
        }
      }
      return response.newBuilder()
        .body(capped.buffer().asResponseBody(body.contentType(), body.contentLength()))
        .build()
    }
  }
}
`
}

function withGuardSource(config) {
  return withDangerousMod(config, ['android', (config) => {
    const pkg = config.android?.package
    if (!pkg) throw new Error('withMapLibreHttpGuard: android.package is not set in app config')
    const dir = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'java', ...pkg.split('.'))
    fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(path.join(dir, `${CLASS_NAME}.kt`), kotlinSource(pkg))
    return config
  }])
}

function withGuardInstall(config) {
  return withMainApplication(config, (config) => {
    let src = config.modResults.contents
    const call = `    ${CLASS_NAME}.install(this)`
    if (!src.includes(call)) {
      // Right after super.onCreate(): before any MapLibre class can be touched.
      src = src.replace(
        /(override fun onCreate\(\) \{\s*\n\s*super\.onCreate\(\)\s*\n)/,
        `$1${call}\n`,
      )
      if (!src.includes(call)) {
        throw new Error('withMapLibreHttpGuard: could not find MainApplication.onCreate() to patch')
      }
    }
    config.modResults.contents = src
    return config
  })
}

const GRADLE_MARK = '// withMapLibreHttpGuard: compile-time visibility of the MapLibre SDK (runtime copy comes from maplibre-react-native)'

function withGuardCompileDep(config) {
  return withAppBuildGradle(config, (config) => {
    let src = config.modResults.contents
    if (src.includes(GRADLE_MARK)) return config
    const { variant, version } = readMapLibreNativeCoords(config.modRequest.projectRoot)
    // Honour a rootProject.ext override the same way the RN module does, so
    // a self-hoster pinning a different MapLibre build keeps both in step.
    const dep = [
      `    ${GRADLE_MARK}`,
      `    compileOnly("org.maplibre.gl:android-sdk-\${rootProject.ext.has('org.maplibre.reactnative.nativeVariant') ? rootProject.ext.get('org.maplibre.reactnative.nativeVariant') : '${variant}'}:\${rootProject.ext.has('org.maplibre.reactnative.nativeVersion') ? rootProject.ext.get('org.maplibre.reactnative.nativeVersion') : '${version}'}")`,
    ].join('\n')
    src = src.replace(/(dependencies\s*\{\s*\n)/, `$1${dep}\n`)
    if (!src.includes(GRADLE_MARK)) throw new Error('withMapLibreHttpGuard: could not find dependencies { } block in app/build.gradle')
    config.modResults.contents = src
    return config
  })
}

module.exports = function withMapLibreHttpGuard(config) {
  return withGuardInstall(withGuardCompileDep(withGuardSource(config)))
}
