/**
 * withAndroidDisableLintVital — Expo config plugin that disables Android
 * Gradle Plugin's "lint vital" analysis for every Android module (the app
 * and every autolinked RN library subproject), not exposed as a plain
 * app.json android.* property.
 *
 * Why: AGP runs `lintVitalAnalyzeRelease` automatically before any release
 * variant assemble/bundle task, as a SEPARATE task per Android subproject
 * (app module AND every RN library with its own build.gradle -- confirmed
 * in CI logs as react-native-community_slider:lintVitalAnalyzeRelease,
 * react-native-ble-plx:lintVitalAnalyzeRelease, etc. all running
 * independently). On a memory-constrained CI runner with
 * org.gradle.parallel=true (screenshots.yml / build-android.yml), several
 * of these ran concurrently and exhausted JVM Metaspace --
 * "OutOfMemoryError: Metaspace" repeating from the Gradle daemon's RMI
 * thread, with the build then hanging effectively forever (no further
 * progress, no clean failure) instead of crashing outright. This is a
 * widely-reported class of failure for local/CI Android release builds,
 * not specific to this app's own code.
 *
 * lint-vital exists to catch fatal lint issues before a release build
 * ships. Store review (Play/Apple) does its own checks regardless, and
 * this only affects local `./gradlew`/`eas build --local` release-variant
 * builds (screenshots + build-android.yml's preview/production profiles)
 * -- not correctness of the shipped app. Run `./gradlew lint` manually if
 * you want lint feedback during development.
 *
 * See https://docs.expo.dev/config-plugins/introduction/ and
 * withProjectBuildGradle's mod docs. Injects into the generated root
 * android/build.gradle (gitignored, regenerated by `expo prebuild`), so
 * it applies to every subproject via Gradle's own `subprojects {}` block
 * -- a single app-module `lintOptions` override would NOT reach the
 * library subprojects that were actually OOMing.
 */
const { withProjectBuildGradle } = require('@expo/config-plugins')

module.exports = function withAndroidDisableLintVital(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language === 'groovy') {
      config.modResults.contents += `
// Injected by withAndroidDisableLintVital.js -- see that file for why.
//
// Deliberately NOT setting android.lintOptions.checkReleaseBuilds (the
// documented DSL flag for this): two different approaches were tried and
// both failed against this AGP version, confirmed via
// './gradlew :react-native-community_slider:assembleRelease --dry-run'
// while developing this fix --
//   1. subprojects { it.afterEvaluate { ... } } -- RN's Gradle plugin
//      (com.facebook.react.rootproject, applied just above) eagerly
//      evaluates every subproject as part of autolinking, so by the time
//      this appended block runs most subprojects are already evaluated:
//      "Cannot run Project.afterEvaluate(Closure) when the project is
//      already evaluated".
//   2. plugins.withId('com.android.library') { ... } (keyed on plugin
//      application, not the evaluation lifecycle -- normally the safe
//      choice for exactly this ordering problem) -- still too late for
//      this specific flag: "It is too late to set checkReleaseBuilds. It
//      has already been read to configure this project."
//
// So instead of touching AGP's DSL/extension at all, disable the already-
// created TASKS directly via the plain Gradle Task API (tasks.matching +
// configureEach), which is lazy and safe at any point regardless of when
// each subproject's variant/lint config gets locked -- this can't hit a
// "too late" error because it never reads or writes the DSL flag AGP is
// protecting, it just marks the resulting task(s) as skipped.
subprojects { subproject ->
    subproject.tasks.matching { it.name.startsWith('lintVital') }.configureEach {
        it.enabled = false
    }
}
`
    }
    return config
  })
}
